# navori:managed start id="managed-drift-watch-base" hash="b1db6dd1" version="0.10.0" source="@navori/core"
#!/usr/bin/env bash
#
# PostToolUse watcher for managed-block drift (#530), on every tool that can
# write a file: `Bash|Edit|Write|NotebookEdit`.
#
# WHY THE MATCHER IS THE WHOLE DECISION, and why it took #775 to widen it. This
# script audits STATE, never the command, so it has no `case "$tool_name"` to
# contradict its registration — the matcher alone decides when it runs, which
# makes a narrow one indistinguishable from a hook that works. It was `Bash`
# only, and the host's own PostToolUse doc spells out the consequence from the
# other direction: a hook matching `Edit|Write` does not run when a `Bash`
# command rewrites the same file. The inverse is the hole this had — in
# `default`/`acceptEdits`, where the host does NOT push everything through the
# shell, an `Edit` over `CLAUDE.md` broke a managed block's hash and this stayed
# quiet until the next Bash call, if one ever came. A session of pure native
# editing put the #523 freeze back into silence, which is the one thing this
# hook exists to prevent.
#
# WHY NOT `FileChanged`, which the same doc section recommends for exactly this
# ("to run a hook when a specific file changes on disk, whatever wrote it").
# The CONTRACT is not the reason, and this comment used to say it was: core can
# register the event today. `lib/config/plugins.ts:91` admits four events, but that
# enum is the schema for a PLUGIN MANIFEST and is used nowhere else —
# `buildClaudeSettings` returns `Record<string, unknown>` and validates no event
# name at all, which is how core already ships `SessionEnd` and
# `UserPromptSubmit`. Only a plugin registering `FileChanged` would need the
# vocabulary widened. Three other things stop it:
#
#   1. The watchlist would live IN the settings, and the managed file set is
#      derived per repo at render time (engine outputs plus every rendered
#      asset, ~60 files here) — so settings.json would carry a second copy of a
#      list this script already derives, and the two would drift. A watchlist
#      that drifts from the managed set is a detector with holes in it, i.e.
#      this hook's own defect class.
#   2. It loses the channel to the model. `FileChanged` has no decision
#      control: the host shows its stderr "to user only", reads `watchPaths`
#      and `systemMessage` out of the JSON output and discards `continue`, and
#      that `systemMessage` is a brief terminal notification that "doesn't
#      reach the SDK message stream". Everything this hook does ends in
#      `exit 2` → stderr → the MODEL, which is what gets the freeze repaired in
#      the same turn. Migrating would downgrade the recipient of the warning.
#   3. Its matcher cannot name these paths. `FileChanged` and `StopFailure` use
#      a narrower exact-match set — letters, digits, `_` and `|` only — and
#      every root this watches (`CLAUDE.md`, `.claude/settings.json`,
#      `.claude/agents/…`) carries a dot, a slash or a hyphen, which drops the
#      matcher onto the regular-expression path. The one viable route is
#      `watchPaths` (absolute paths) returned from `SessionStart`, which is
#      more machinery and still subject to (1) and (2).
#
# What the widening does NOT buy, stated plainly: a write from outside the
# session — a formatter in a watch process, another terminal — still surfaces
# only on the next tool call navori sees. `FileChanged` would catch that one.
# The cost of what it does buy is one shasum pass (~35ms, quoted below) per
# native edit.
#
# THIS HOOK NEVER READS THE COMMAND. That is the whole design. Its sibling
# `guard-destructive.sh` decides by the SHAPE of what you typed, so it only ever
# covers the write verbs someone enumerated — `>`, `sed -i`, `tee` — and misses
# `python -c`, `perl -i`, `awk > file`, a formatter, or a script the agent
# didn't write. The blind audit found that "describe the danger by its textual
# form" pattern eight times, four of them with a test pinning the hole shut.
#
# So this one asks the only question that has no form: AFTER the command ran,
# do navori's managed blocks still hash to what their markers claim? A block
# whose body changed is a block navori will refuse to update from now on
# (`user-modified-skipped`) — the #523 freeze, arriving in silence. Whatever
# rewrote it, legitimately or not, this notices.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
#
# SCOPE. settings.json invokes hooks as `bash "$CLAUDE_PROJECT_DIR/.claude/…"`,
# so this process starts in the MAIN repo even when the command ran inside an
# agent worktree (#454). Checking the main mirror is the right default — that is
# the copy every session shares and the one a stray write actually freezes — but
# a block broken INSIDE a worktree is not seen here. It surfaces when that branch
# is rendered or reviewed.
#
# COST, and why this compares CONTENT rather than mtimes. The obvious cheap
# check is `find -newer <stamp>`, and it is wrong here: `find` compares mtimes at
# whatever resolution the filesystem stores, which on several (ext4 under the CI
# runner among them) is ONE SECOND. Two writes inside the same second as the
# stamp are invisible — the watcher would report the first and silently miss the
# second, which is precisely the failure it exists to prevent. It passed on APFS
# and failed in CI, so the clock was never a sound basis.
#
# So the common case costs one `shasum` pass over the managed files (~35ms) and
# compares that list against the previous one. It is exact, it depends on no
# clock, and per-block hashing — the expensive part, ~3.5s for 53 blocks — runs
# ONLY for the files whose content actually changed, which in a normal session
# is none and in a bad one is one. That ~35ms is the MEDIAN of 13,692 recorded
# runs in `~/.navori/audits` (mean 43.7ms, p95 78ms); the "~25ms measured over
# 60 files" this used to quote was a single early sample and ran ~40% optimistic.
set -uo pipefail

# The tools this state auditor must run after, i.e. the matcher it has to be
# registered with. Read by `hook-matcher-wiring.test.ts` (#796); nothing in this
# script reads it.
#
# It exists because this hook has nothing else the wiring suite can derive an
# invariant from. A hook that dispatches on `case "$tool_name"` contradicts a
# narrow matcher by itself, and a gate that declares `$TRIGGER_TOKENS` claims
# the commands it needs handed to it — this one audits STATE, so it makes
# neither claim, and its matcher was held up only by a hand-written list of four
# tool names in `build-settings.test.ts`. Narrowing the matcher went red there
# and the obvious repair was to edit the literal, which is the drift this
# declaration removes: the edit point is now the script, where the intent lives.
#
# The rule could not be inferred from silence instead. "Every hook with no
# `case` and no `$TRIGGER_TOKENS` must receive every write tool" falsifies
# against `guard-destructive.sh` and `subagent-stop-handoff.sh` (matcher
# `Agent|Task`, correct by design).
COVERED_TOOLS='Bash Edit Write NotebookEdit'

# PostToolUse delivers its payload on stdin; this hook never needed it and the
# audit recorder does (session_id/cwd), so it is captured rather than ignored.
payload=$(cat 2>/dev/null) || payload=""

navori_audit_name="managed-drift-watch"
navori_audit_phase="PostToolUse"
# The recorded tool used to be the literal "Bash", which was true while the
# matcher was. Now that four tools reach here it has to be read — and read
# without a fork, because this runs after every tool call: `#` and `%%` are
# builtins, and a tool name carries no quote to escape. Anything the parse does
# not recognise leaves the field EMPTY (the partial then omits it) rather than
# guessing, since a wrong label in the audit log is how a lane gets measured as
# working when it is not — this issue, one level up.
navori_audit_tool=""
case "$payload" in
  *'"tool_name":"'*)
    navori_audit_tool=${payload#*'"tool_name":"'}
    navori_audit_tool=${navori_audit_tool%%'"'*}
    case "$navori_audit_tool" in
      "" | *[!A-Za-z_]*) navori_audit_tool="" ;;
    esac
    ;;
esac
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/render/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  # The third field is the OWNER, and it is never empty: inside a subagent the
  # host sends a real `agent_id`; on the main thread it sends none and the
  # literal below names the orchestrator explicitly.
  #
  # It used to be `// ""`, and the empty case did not stay empty — it came out
  # as the `cwd`. Command substitution strips trailing newlines, so an empty
  # third field left `$navori_audit_fields` with only two lines; then
  # `${rest#*<NL>}` found no newline in `"cwd"` and POSIX says a `#` pattern
  # that does not match returns the string UNCHANGED. 41,581 of the park's
  # 52,460 recorded owners (79%) were a filesystem path for that reason.
  #
  # The consumer's behaviour does not change — `ownerOf` looks the value up
  # among the session's agents and sends anything that names nobody to the
  # orchestrator, which is where a path already went — but the record stops
  # claiming the repo directory is an agent. Old logs keep working through the
  # same "names nobody" branch.
  #
  # The trailing "." is a sentinel, not data: with it the third field is always
  # followed by a newline, so the `%%` below cannot fall into the same trap if
  # a future field is ever empty.
  #
  # The owner is picked with an explicit "first non-empty string", NOT with
  # `.agent_id // .subagent_id // "orchestrator"`. In jq only `null` and `false`
  # are falsy, so a host that sends the key with an EMPTY string satisfies `//`
  # and the chain yields `""` — the field then disappears from the record and
  # `ownerOf` falls back to the time window, which is the guess this field
  # exists to avoid. Caught by a test, not by review.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", ([.agent_id, .subagent_id] | map(select(type == "string" and . != "")) | first) // "orchestrator", .tool_use_id // "", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_tool_use_id=${navori_audit_rest%%
*}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  if [ ! -f "$navori_audit_file" ]; then
    # SPOOL for the phase that CANNOT have a log yet (#778).
    #
    # `navori audit --start` is what creates the session log, and it runs from
    # the UserPromptSubmit hook — i.e. after the first prompt. Every SessionStart
    # hook therefore fires BEFORE the file exists, and the check above threw its
    # record away every single time: measured, `session-start-context` recorded 1
    # of ~20 startups in this repo, and the only survivor was a resume onto an
    # already-open log. "Did the session load the harness?" had no witness at all,
    # which is exactly the question the recorder exists to answer.
    #
    # So those records go to a side file that `--start` absorbs. Two deliberate
    # limits keep this from becoming a leak:
    #
    #   1. SessionStart ONLY. Every other phase runs after a prompt, so a missing
    #      log there means the session is genuinely not marked — and spooling
    #      those would write four lines per Bash call, for every session of every
    #      repo, forever. That is thousands of writes to buy nothing.
    #   2. Only where the repo's audit directory ALREADY exists, which means the
    #      repo has been audited (or armed) at least once. `mkdir` is never run
    #      from here: a repo that has never used audit-mode must stay at zero
    #      files and zero forks, the same contract as the root gate above. The
    #      cost is that the FIRST audited session of a repo still loses its
    #      SessionStart records; every one after it has them.
    #
    # FAIL-OPEN, and here more than anywhere: this runs while a session is
    # opening. Every failure path below returns 0 and writes nothing to stdout —
    # a spool that could abort a hook would make observation the reason a session
    # does not start, which is the one bug this partial may never have.
    [ "${navori_audit_phase:-}" = "SessionStart" ] || return 0
    [ -d "$navori_audit_root/$navori_audit_repo" ] || return 0
    navori_audit_file=$navori_audit_root/$navori_audit_repo/pending-$navori_audit_session.jsonl
    if [ ! -e "$navori_audit_file" ]; then
      : >> "$navori_audit_file" 2>/dev/null || return 0
    fi
  fi
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  # `tsMs` is the instant at the resolution the log actually needs (#685): the
  # `ts` below truncates to the second, and 84% of a measured session's events
  # share their second with another one. This value is already computed — the
  # duration above is derived from it — so recording it costs nothing.
  #
  # Validated with the same `-ge 0` idiom as `ms`, and for the same reason: it
  # is passed as `--argjson`, so a non-numeric value would make the whole `jq`
  # fail and the event would vanish instead of merely losing a field.
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0

  # `ts` is NOT stamped here, and that is the whole point of #696: it was a
  # `date` fork per event — 46,850 of them across this store — for a string
  # fully derivable from the `tsMs` above, which `$EPOCHREALTIME` already
  # produced without spawning anything. The file's own cost doctrine (see
  # `navori_audit_now`) says spend a process only when there is no other way;
  # keeping this one made the comment lie four lines under the value that
  # refutes it.
  #
  # Nothing downstream lost a field: `parse.ts` derives the ISO from `tsMs`
  # when the record carries none, and logs written before this still have
  # theirs. The lifecycle records — `start`, `stop`, `session-end` — keep a real
  # `ts`, so a human reading the raw `.log` still has dated anchors; those are
  # ~3 per session, not one per hook.
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --arg toolUseId "${navori_audit_tool_use_id:-}" \
    --argjson ms "$navori_audit_ms" \
    --argjson tsMs "$navori_audit_end" \
    '{tsMs:$tsMs,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)
     + (if $toolUseId == "" then {} else {toolUseId:$toolUseId} end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

# This hook has SEVEN early exits (no sha, no roots, no changes, …). Wiring a
# call into each is how the set drifts the next time one is added, so the verdict
# is derived once, from the exit code, in a trap.
#
# `navori_audit_reached_check` is what separates "ran and found nothing" from
# "bailed before checking anything" — the distinction the whole exercise exists
# for. Without it every early exit would report `clean`, i.e. would claim a
# verification that never happened.
navori_audit_reached_check=0
navori_audit_on_exit() {
  navori_audit_code=$?
  if [ "$navori_audit_code" -eq 2 ]; then
    navori_audit_log "dirty" "bloque managed con hash desalineado"
  elif [ "$navori_audit_reached_check" -eq 1 ]; then
    navori_audit_log "clean"
  else
    navori_audit_log "skip" "sin nada que verificar"
  fi
  return 0
}
trap navori_audit_on_exit EXIT

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

stamp=".claude/.managed-drift-stamp"

# sha1 tool, resolved once. `shasum` on macOS, `sha1sum` on most Linuxes; both
# print `<hash>  <path>` for a file list, which is the format the stamp stores.
sha=""
command -v shasum >/dev/null 2>&1 && sha="shasum -a 1"
[ -z "$sha" ] && command -v sha1sum >/dev/null 2>&1 && sha="sha1sum"
# No sha tool: stay silent. This is a detector, not a gate — the guard still
# sits in front, and a noisy failure here would fire on every single command.
[ -z "$sha" ] && exit 0

# The marker-carrying outputs of `ENGINE_OUTPUTS` (lib/health.ts) — the same
# list the guard's rule 6 protects, and for the same reason.
#
# `.claude/progress/` and `.codex/progress/` are deliberately absent for BOTH
# engines: those are agent handoff files, they carry no markers, and every
# subagent writes one — including them would re-hash a fresh report on every
# command and find nothing. `.claude/worktrees/` too: each is a full checkout,
# so walking it would make this hook cost more than the command it follows. That
# is why `.codex` is NOT listed wholesale.
roots=""
for r in CLAUDE.md AGENTS.md .claude/settings.json .claude/agents .claude/skills .claude/hooks .agents/skills .codex/config.toml .codex/agents .codex/hooks .cursor/rules; do
  [ -e "$r" ] && roots="$roots $r"
done
[ -z "$roots" ] && exit 0

# shellcheck disable=SC2086 — word splitting is how the root list is passed.
current=$(find $roots -type f -exec $sha {} + 2>/dev/null | sort || true)
[ -z "$current" ] && exit 0

# First run in a session (or after the ephemeral dir was wiped): adopt the
# current state as the baseline and say nothing. Reporting every block on the
# first command would train the reader to ignore this hook by lunchtime.
if [ ! -f "$stamp" ]; then
  mkdir -p .claude 2>/dev/null || exit 0
  printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
  exit 0
fi

# Lines present now but not in the baseline: a file whose CONTENT changed, or a
# new one. A deleted file appears only in the baseline and is ignored — there is
# no block left to verify.
changed=$(printf '%s\n' "$current" | grep -F -x -v -f "$stamp" 2>/dev/null | sed -E 's/^[a-f0-9]+[[:space:]]+//' || true)
# Re-baseline BEFORE reporting, so one write is reported once instead of on
# every command for the rest of the session. A second write does change the
# content again, and does get its own report.
printf '%s\n' "$current" > "$stamp" 2>/dev/null || true
[ -z "$changed" ] && exit 0

# From here on the work is per-CHANGED-file only. `$(…)` strips the trailing
# newline, which is what makes these hashes agree with `computeManagedHash`
# (lib/render/marker.ts: sha1 over the body with trailing whitespace removed, first 8
# hex); without it every hash differs and the hook cries wolf on healthy files.
drift=""
while IFS= read -r file; do
  [ -n "$file" ] || continue
  # Both marker syntaxes (lib/render/marker.ts): HTML for markdown, `#` for scripts and
  # TOML. Anchored at the start of the line so a block QUOTED inside prose —
  # this file's own header, a skill that documents the format — is not read as a
  # real marker.
  while IFS='|' read -r id declared; do
    [ -n "$id" ] || continue
    body=$(awk -v id="$id" '
      $0 ~ ("^<!-- navori:managed id=\"" id "\"") { f=1; next }
      $0 ~ ("^# navori:managed start id=\"" id "\"") { f=1; next }
      $0 ~ ("^<!-- /navori:managed id=\"" id "\"") { f=0 }
      $0 ~ ("^# navori:managed end id=\"" id "\"") { f=0 }
      f' "$file")
    actual=$(printf '%s' "$body" | $sha | cut -c1-8)
    [ "$actual" = "$declared" ] || drift="${drift}
  ${file}  block '${id}'  (marker says ${declared}, content hashes ${actual})"
  done <<EOF
$(grep -oE '^(<!-- navori:managed|# navori:managed start) id="[^"]+" hash="[a-f0-9]+"' "$file" 2>/dev/null \
  | sed -E 's/.*id="([^"]+)" hash="([a-f0-9]+)".*/\1|\2/')
EOF
done <<EOF
$changed
EOF

navori_audit_reached_check=1
[ -z "$drift" ] && exit 0

# Exit 2 so the text reaches the model rather than scrolling past in a log: the
# whole failure mode being cured is that this goes unnoticed. The command has
# already run — nothing is being reverted or retried.
cat >&2 <<MSG
navori: a managed block no longer matches its marker hash.${drift}

navori will now treat those blocks as hand-edited and STOP updating them (the
#523 freeze). Nothing reverted this for you.

Recover with 'navori sync' (reconciles, shows the conflict diff) or
'navori render --apply' if the block should simply be regenerated. If the edit
was intentional, it belongs in the source asset, not in the rendered mirror.
MSG
exit 2
# navori:managed end id="managed-drift-watch-base"
