# navori:managed start id="qg-pre-commit-base" hash="524f8d74" version="0.11.1" source="@navori/core"
#!/usr/bin/env bash
#
# Pre-commit / pre-push quality gate hook.
# Reads the tool input (from Claude Code's PreToolUse Bash matcher) and runs
# the project's `qualityGate.fast` command before allowing the commit.
#
# It does NOT verify the reviewer's content receipt. That backstop lived here
# until #365 and was removed on purpose: five fail-open paths (worktree, Codex
# workspace, zsh word-splitting, non-ASCII paths, a truncated singleton receipt)
# against zero documented catches, and one of its failure modes blocked every
# PR in the repo. The receipt is a handoff between the `reviewer` and the
# `publisher`, which verifies it agent-side and re-signs the delta. Don't
# re-add the check here without a captured case it would have caught.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific checks in the user section at the
# bottom — they keep `cmd` and the original exit codes in scope.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
# `${payload-$(cat)}` (unset test, not `:-`) rather than an unconditional
# `payload=$(cat)`: a caller that already captured stdin itself (spec 0035 —
# `managed-drift-watch.sh` needs the audit recorder's session_id/cwd even on
# tool names this hook does not otherwise read) keeps that value, empty or
# not, instead of this partial re-reading an already-drained pipe and
# clobbering it with "".
payload=${payload-$(cat)}
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
cmd=$(extract_cmd)
# Spec 0035 D2 — the single payload adapter shared by every hook that needs an
# engine-specific value. Inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts).
# Single source of truth for the Claude/Codex normalization; DO NOT copy this
# body back into a hook by hand or branch on the engine inside a hook — D2
# rejected per-script `if codex …` branches (12 copies of the same logic,
# each one a place to drift).
#
# `nv_engine` is decided by WHERE THE HOOK SCRIPT LIVES ON DISK, not by the
# payload's shape (a `turn_id`/`apply_patch` sniff breaks the day Claude ships
# a field with the same name — see design.md's "Descartado") and not by an
# env var prefix on the registered command (that would change the `command`
# string Codex hashes for `trusted_hash`, un-approving every hook a repo
# already trusted — see hook-registrations.ts's module doc). The registered
# command is always `bash ".../.codex/hooks/<script>.sh"` or
# `bash "$CLAUDE_PROJECT_DIR/.claude/hooks/<script>.sh"`. `$0` — not
# `BASH_SOURCE`, which zsh (#391: hooks run under bash AND zsh) leaves unset
# under `set -u` — is the path the invoking shell was given, and
# `comment-draft-confirm.sh` already established this exact pattern.
#
# Depends on `payload`/`payload_field` (the `extract-cmd` partial): include
# `extract-cmd` in the same script whenever this partial's helpers are used —
# `payload_field` is only CALLED here (inside functions), never at top level,
# so include order between the two partials does not matter.
case "$0" in
  *".codex/hooks/"*) nv_engine=codex ;;
  *) nv_engine=claude ;;
esac

if [ "$nv_engine" = codex ]; then
  nv_cwd=$(payload_field cwd)
  # `cwd` is the session's working dir, which may be a workspace subdir in a
  # monorepo; the project root is always the git toplevel from there. Falls
  # back to the raw cwd outside a git work tree rather than failing closed.
  nv_project_dir=$(git -C "${nv_cwd:-.}" rev-parse --show-toplevel 2>/dev/null) || nv_project_dir=${nv_cwd:-.}
else
  nv_project_dir=${CLAUDE_PROJECT_DIR:-}
fi

# Runtime handoffs have one engine-neutral home. The caller composes this
# relative path with its checkout root; legacy roots remain readable only.
nv_progress_dir=".navori/state/handoffs"

# The Claude-equivalent tool name for the CURRENT PreToolUse/PostToolUse
# payload (D2: apply_patch -> Edit, spawn_agent -> Agent, everything else
# unchanged — `mcp__…` names and `Bash` already match on both engines).
nv_tool() {
  local raw
  raw=$(payload_field tool_name)
  if [ "$nv_engine" = codex ]; then
    case "$raw" in
      apply_patch) printf 'Edit' ;;
      spawn_agent) printf 'Agent' ;;
      *) printf '%s' "$raw" ;;
    esac
  else
    printf '%s' "$raw"
  fi
}

# Paths the current tool call touches, one per line (possibly none). Claude
# carries them as `tool_input.file_path` / `tool_input.notebook_path`; Codex's
# `apply_patch` has no such field — the whole patch is `tool_input.command`,
# and the paths live in its `*** Add File:` / `*** Update File:` /
# `*** Delete File:` / `*** Move to:` headers (codex-rs's apply_patch parser).
nv_edited_paths() {
  if [ "$nv_engine" = codex ]; then
    payload_field tool_input.command | sed -nE \
      's/^\*\*\* (Add File|Update File|Delete File|Move to): (.*)$/\2/p'
  else
    local fp nb
    fp=$(payload_field tool_input.file_path)
    nb=$(payload_field tool_input.notebook_path)
    [ -n "$fp" ] && printf '%s\n' "$fp"
    [ -n "$nb" ] && printf '%s\n' "$nb"
  fi
}

# The subagent type of the current call. Claude: `tool_input.subagent_type`
# (PreToolUse Agent/Task). Codex: `tool_input.agent_type` in PreToolUse
# (spawn_agent), or the top-level `agent_type` Codex adds to SubagentStop.
nv_subagent_type() {
  if [ "$nv_engine" = codex ]; then
    local t
    t=$(payload_field tool_input.agent_type)
    [ -n "$t" ] || t=$(payload_field agent_type)
    printf '%s' "$t"
  else
    payload_field tool_input.subagent_type
  fi
}

# Deliberately NO `nv_emit_context` helper here. `hook-output-contract.test.ts`
# ("los partials no hablan con el host, solo escriben al log") holds every
# `_partials/*.sh` file to zero host-output vocabulary — a partial is inlined
# BEFORE the per-script, per-event output contract is known, so it must never
# construct `hookSpecificOutput`/`systemMessage` itself. Every hook this spec
# touches already builds its own JSON at its own call site (unchanged by D2);
# a script whose Claude/Codex registrations differ in event name (D1: e.g.
# `subagent-stop-handoff` is PostToolUse under Claude, SubagentStop under
# Codex) is unaffected in practice — Codex does not honor `additionalContext`
# on `SubagentStop` at all (codex-research.md), so `systemMessage` is what a
# human sees there regardless of which literal `hookEventName` the JSON claims.

navori_audit_name="quality-gate-pre-commit"
navori_audit_phase="PreToolUse"
navori_audit_tool="Bash"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/render/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  # The third field is the OWNER, and it is never empty: inside a subagent the
  # host sends a real `agent_id`; on the main thread it sends none and the
  # literal below names the orchestrator explicitly.
  #
  # It used to be `// ""`, and the empty case did not stay empty — it came out
  # as the `cwd`. Command substitution strips trailing newlines, so an empty
  # third field left `$navori_audit_fields` with only two lines; then
  # `${rest#*<NL>}` found no newline in `"cwd"` and POSIX says a `#` pattern
  # that does not match returns the string UNCHANGED. 41,581 of the park's
  # 52,460 recorded owners (79%) were a filesystem path for that reason.
  #
  # The consumer's behaviour does not change — `ownerOf` looks the value up
  # among the session's agents and sends anything that names nobody to the
  # orchestrator, which is where a path already went — but the record stops
  # claiming the repo directory is an agent. Old logs keep working through the
  # same "names nobody" branch.
  #
  # The trailing "." is a sentinel, not data: with it the third field is always
  # followed by a newline, so the `%%` below cannot fall into the same trap if
  # a future field is ever empty.
  #
  # The owner is picked with an explicit "first non-empty string", NOT with
  # `.agent_id // .subagent_id // "orchestrator"`. In jq only `null` and `false`
  # are falsy, so a host that sends the key with an EMPTY string satisfies `//`
  # and the chain yields `""` — the field then disappears from the record and
  # `ownerOf` falls back to the time window, which is the guess this field
  # exists to avoid. Caught by a test, not by review.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", ([.agent_id, .subagent_id] | map(select(type == "string" and . != "")) | first) // "orchestrator", .tool_use_id // "", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_tool_use_id=${navori_audit_rest%%
*}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  if [ ! -f "$navori_audit_file" ]; then
    # SPOOL for the phase that CANNOT have a log yet (#778).
    #
    # `navori audit --start` is what creates the session log, and it runs from
    # the UserPromptSubmit hook — i.e. after the first prompt. Every SessionStart
    # hook therefore fires BEFORE the file exists, and the check above threw its
    # record away every single time: measured, `session-start-context` recorded 1
    # of ~20 startups in this repo, and the only survivor was a resume onto an
    # already-open log. "Did the session load the harness?" had no witness at all,
    # which is exactly the question the recorder exists to answer.
    #
    # So those records go to a side file that `--start` absorbs. Two deliberate
    # limits keep this from becoming a leak:
    #
    #   1. SessionStart ONLY. Every other phase runs after a prompt, so a missing
    #      log there means the session is genuinely not marked — and spooling
    #      those would write four lines per Bash call, for every session of every
    #      repo, forever. That is thousands of writes to buy nothing.
    #   2. Only where the repo's audit directory ALREADY exists, which means the
    #      repo has been audited (or armed) at least once. `mkdir` is never run
    #      from here: a repo that has never used audit-mode must stay at zero
    #      files and zero forks, the same contract as the root gate above. The
    #      cost is that the FIRST audited session of a repo still loses its
    #      SessionStart records; every one after it has them.
    #
    # FAIL-OPEN, and here more than anywhere: this runs while a session is
    # opening. Every failure path below returns 0 and writes nothing to stdout —
    # a spool that could abort a hook would make observation the reason a session
    # does not start, which is the one bug this partial may never have.
    [ "${navori_audit_phase:-}" = "SessionStart" ] || return 0
    [ -d "$navori_audit_root/$navori_audit_repo" ] || return 0
    navori_audit_file=$navori_audit_root/$navori_audit_repo/pending-$navori_audit_session.jsonl
    if [ ! -e "$navori_audit_file" ]; then
      : >> "$navori_audit_file" 2>/dev/null || return 0
    fi
  fi
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  # `tsMs` is the instant at the resolution the log actually needs (#685): the
  # `ts` below truncates to the second, and 84% of a measured session's events
  # share their second with another one. This value is already computed — the
  # duration above is derived from it — so recording it costs nothing.
  #
  # Validated with the same `-ge 0` idiom as `ms`, and for the same reason: it
  # is passed as `--argjson`, so a non-numeric value would make the whole `jq`
  # fail and the event would vanish instead of merely losing a field.
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0

  # `ts` is NOT stamped here, and that is the whole point of #696: it was a
  # `date` fork per event — 46,850 of them across this store — for a string
  # fully derivable from the `tsMs` above, which `$EPOCHREALTIME` already
  # produced without spawning anything. The file's own cost doctrine (see
  # `navori_audit_now`) says spend a process only when there is no other way;
  # keeping this one made the comment lie four lines under the value that
  # refutes it.
  #
  # Nothing downstream lost a field: `parse.ts` derives the ISO from `tsMs`
  # when the record carries none, and logs written before this still have
  # theirs. The lifecycle records — `start`, `stop`, `session-end` — keep a real
  # `ts`, so a human reading the raw `.log` still has dated anchors; those are
  # ~3 per session, not one per hook.
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --arg toolUseId "${navori_audit_tool_use_id:-}" \
    --argjson ms "$navori_audit_ms" \
    --argjson tsMs "$navori_audit_end" \
    '{tsMs:$tsMs,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)
     + (if $toolUseId == "" then {} else {toolUseId:$toolUseId} end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin
# Can this gate hand a no-verdict outcome to the user instead of blocking?
# Inlined at render time (see lib/render/hook-includes.ts). Decides only; the
# JSON that speaks to the host stays in each script (partials never carry host
# output vocabulary — hook-output-contract.test.ts).
#
# WHY (#1117): when the TOOL failed (scanner missing a flag, declared runner not
# on PATH) the gate has no verdict, and "run it yourself outside the agent" is a
# dead end. Claude Code's PreToolUse can ask the human; that is the right exit.
#
# Returns 0 only when ALL hold; any doubt is "no", and "no" is today's block:
#   - the script is not a Codex copy (Codex drops `permissionDecision`, so an
#     ask there would let the call PROCEED unasked). Decided by WHERE THE SCRIPT
#     LIVES, the same rule as the hook-input partial; hooks live in `.codex/hooks/`,
#     plugin scripts in `.codex/scripts/`.
#   - the payload is a real PreToolUse hook call. A git hook or the CLI
#     (`</dev/null`) has no payload, so there is nobody to ask.
#   - jq exists to build the reason JSON safely; without it, block.
# Needs `payload`/`payload_field` from the extract-cmd partial.
navori_can_ask() {
  case "$0" in
    *".codex/hooks/"* | *".codex/scripts/"*) return 1 ;;
  esac
  command -v jq >/dev/null 2>&1 || return 1
  [ "$(payload_field hook_event_name)" = "PreToolUse" ]
}

# This hook fires on EVERY Bash call and does real work on almost none of them,
# so its verdict is derived from the exit code in a trap rather than from a call
# per branch — the branch set here is the one most likely to grow.
#
# `navori_audit_ran_gate` is the distinction that matters: the recorded `ms` of a
# run that actually executed the gate (tens of seconds) means something very
# different from that of a run that looked at the command and moved on (single
# digits). Collapsing both into `allow` would make the timing unreadable.
navori_audit_ran_gate=0
navori_audit_skip_reason="el comando no es un commit"
# Set when the gate had NO verdict (runner missing) and the user was asked (#1117).
navori_audit_ask_reason=""
navori_audit_on_exit() {
  navori_audit_code=$?
  # A cancelled hook reaches this trap with `$?` == 0 (#797), so the exit code
  # below cannot tell "finished green" from "was killed mid-gate". The signal
  # handler can, it already recorded the run, and it is the only witness of the
  # two that saw what happened.
  if [ -n "${navori_audit_signal:-}" ]; then
    return 0
  fi
  if [ "$navori_audit_code" -ne 0 ]; then
    navori_audit_log "block" "el quality gate no paso o no pudo correr" || true
  elif [ -n "$navori_audit_ask_reason" ]; then
    navori_audit_log "ask" "$navori_audit_ask_reason" || true
  elif [ "$navori_audit_ran_gate" -eq 1 ]; then
    navori_audit_log "allow" "gate ejecutado y verde" || true
  else
    navori_audit_log "skip" "$navori_audit_skip_reason" || true
  fi
  return 0
}
trap navori_audit_on_exit EXIT
# Signal traps (TERM/INT/HUP) + `navori_audit_signal`. Shared body, single
# source of truth: the three gates are killed the same way and must record it
# the same way.
# Shared "the host cancelled this hook" recorder — inlined into the three gate
# hooks at render time (see the include directive in the source scripts +
# lib/render/hook-includes.ts).
#
# WHY (#797): a `command` hook that reaches its host timeout is CANCELLED, and
# bash still runs the EXIT trap on the way out with `$?` == 0 — the last
# COMPLETED command was the `trap` builtin itself. So the recorder's "exit code
# is zero" branch recorded a gate aborted after 3 seconds of a 20-second run as
# `allow`, "gate ejecutado y verde". Reproduced end to end on the RENDERED hook;
# the only trace of the truth was an `ms` nobody reads.
#
# That false green is worse than the absence it replaced: `quality-gate-aborted`
# only fires on a `gate-started` with NO terminal record, so the fake `allow`
# satisfied the detector and disarmed it. The signal itself is therefore the
# witness — recorded here, before the process dies, under its own verdict
# (`gate-killed`): never `allow`, never `block`. Nothing was validated, and the
# host had already discarded this hook's output when it sent the signal.
#
# The docs do not say WHICH signal the host uses to cancel, so this covers the
# handled ones (TERM/INT/HUP) while `gate-started` keeps covering SIGKILL, which
# no handler can ever observe. Both halves are needed: either one alone detects
# a scenario that may not be the one that happens.
#
# FAIL-OPEN like everything else in the recorder: the handler records, re-raises
# the ORIGINAL signal with its default disposition — so the process still dies
# from what it was sent instead of continuing as if nothing happened — and never
# changes what the host does with the tool call. It is deliberately NOT a
# process-tree kill: the gate's own child (`pnpm lint`, `semgrep`, `jscpd`)
# already outlives the hook today, and killing someone else's build from an
# observer is a decision of its own (#797, residue 3).
#
# SIGNAL DEFERRAL, so the recorded `ms` is not read as a second lie: bash does
# not run a trap while it waits for a foreground command, so under bash the
# record lands when the gate command FINISHES, not when the signal arrived. The
# verdict is the same either way and the host is long gone by then; only the
# instant differs.
#
# `navori_audit_signal` is what keeps the two recorders from both writing: the
# EXIT trap runs after this one and must stay quiet, since its `$?` is exactly
# the value that cannot be trusted here.
navori_audit_signal=""
navori_audit_on_signal() {
  navori_audit_signal=$1
  navori_audit_log "gate-killed" "cancelado por SIG$1: nada quedo validado" || true
  # `|| true` on both: a recorder may never become the reason a hook fails, and
  # `set -e` is on in every script that includes this.
  trap - "$1" 2>/dev/null || true
  kill -s "$1" "$$" 2>/dev/null || true
  return 0
}
trap 'navori_audit_on_signal TERM' TERM
trap 'navori_audit_on_signal INT' INT
trap 'navori_audit_on_signal HUP' HUP

# Detect the project's REAL package manager from lockfiles / package.json, so a
# gate command hardcoded to one PM (e.g. `pnpm run ...`) can still run in a repo
# that actually uses another (e.g. bun). Mirrors lib/detect.ts precedence:
# `packageManager` field first, then pnpm/bun/yarn/npm lockfiles. Prints the PM
# name (or nothing) on stdout. Git runs hooks from the repo root, so relative
# paths resolve against the project root.
detect_pm() {
  if [ -f package.json ]; then
    pm=$(sed -n 's/.*"packageManager"[[:space:]]*:[[:space:]]*"\([a-z]*\)@.*/\1/p' package.json | head -n1)
    case "$pm" in pnpm|npm|yarn|bun) printf '%s' "$pm"; return 0 ;; esac
  fi
  if [ -f pnpm-lock.yaml ]; then printf 'pnpm'; return 0; fi
  if [ -f bun.lockb ] || [ -f bun.lock ]; then printf 'bun'; return 0; fi
  if [ -f yarn.lock ]; then printf 'yarn'; return 0; fi
  if [ -f package-lock.json ]; then printf 'npm'; return 0; fi
  return 0
}

# True when the argument is a JS package manager (so we only try to remap the
# leading token of the gate command when it's actually a PM, not `make`/`ruff`).
is_pm() {
  case "$1" in pnpm|npm|yarn|bun) return 0 ;; *) return 1 ;; esac
}

run_gate() {
  navori_audit_ran_gate=1
  # The host can kill this process at its hook timeout, before our EXIT trap
  # records allow/block. Persist a start marker first; audit correlates it with
  # the terminal record by tool_use_id and reports an unfinished gate.
  navori_audit_log "gate-started" "inicio del quality gate" || true
  echo "[navori] running quality-gate fast: $1" >&2
  eval "$1" || {
    echo "[navori] quality-gate fast failed. Commit aborted." >&2
    exit 2
  }
}

# Gate to `git commit` only. $TRIGGER_RE is consumed by the shared detector
# inlined below.
TRIGGER_RE='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'
# Literal substrings every branch of $TRIGGER_RE needs; read by the fast
# path in the shared detector below (spec 0016). Keep NEXT to the regex:
# a branch added there without its token here silently loses the shortcut
# (fail-open to the slow path), and the inlined tests pin the pairing.
TRIGGER_TOKENS='commit'
# Heredoc bodies fed to `cat` are data, not commands (#1095).
TRIGGER_STRIP_HEREDOC_BODIES=1
# Shared gate detector — inlined into each hook at render time (see the include
# directive in the source scripts + lib/render/hook-includes.ts). The caller MUST set
# $TRIGGER_RE (an ERE) before the include; it decides which git ops this hook
# gates. Single source of truth for the FIX B/C wrapper-peeling logic; DO NOT
# copy this body into a hook by hand.
#
# Detect whether $1 (a possibly-compound command) invokes a gated operation.
# Splits $1 on the shell separators && || ; | and newlines, strips leading
# whitespace plus wrapper words (`(`, `\`, `command `) and `VAR=value` env
# prefixes from each segment, and returns 0 if ANY segment STARTS with a gated
# `git …` invocation on a word boundary (matched by $TRIGGER_RE). Replaces
# literal-prefix `case` matching, which silently skipped the gate for
# `cd x && git commit`, `echo y; git push`, or a leading space (#88: NEVER skip
# the gate silently). Matching a segment START means a quoted `echo "git commit"`
# does NOT trigger it. Known limitation: it cannot see through `sh -c`, `eval`,
# or obfuscation — a seatbelt, not a sandbox.
#
# Heredoc bodies (#1095): when the caller sets TRIGGER_STRIP_HEREDOC_BODIES=1,
# the body of a `cat <<TAG … TAG` heredoc is DATA, not commands, so a
# `git commit` line inside e.g. a `gh issue create --body "$(cat <<'EOF' …`
# no longer counts. It is an ALLOW-list on purpose: only a `cat` heredoc (bare,
# or inside `$(…)` of gh/git/echo/printf) with nothing chained after it is
# stripped; anything else — `bash <<EOF`, `while read c; do $c; done <<EOF`,
# `cat <<EOF | sh`, `python - <<EOF` — keeps its body, because a shell or
# interpreter may execute it. Opt-in because master-accept-confirm matches
# unanchored and must keep seeing bodies fed to a non-shell interpreter.
# The fast path on its own, so a caller can apply it EARLIER than the segment
# scan — before it has even paid to extract the command from the payload.
#
# Returns 0 when $1 may contain a gated operation, 1 when it provably cannot.
# The argument is the one the block below spells out: no $TRIGGER_RE can match
# without one of the caller's literal TOKENS appearing in the segment it
# matches, and every segment is a substring of the input. So the absence of
# every token is proof that no segment can match — and the same proof holds one
# level up, over the raw PAYLOAD the command was extracted from: JSON escaping
# touches `"`, `\` and control characters, never the letters of a token.
#
# Disarms when $TRIGGER_TOKENS is unset: with no tokens declared there is
# nothing to prove absent, so it answers "maybe" and the caller does the work.
# Fail-open to the SLOW path, never to a skip.
has_trigger_token() {
  [ -n "${TRIGGER_TOKENS:-}" ] || return 0
  # Token iteration goes through newline-split + `read`, NOT `for _tok in
  # $TRIGGER_TOKENS`: zsh does not word-split an unquoted expansion, so the
  # `for` form iterated ONCE with the whole list as a single token there — and
  # a token that can never match is a gate that never fires. Caught by the
  # bash×zsh differential suite.
  local _input="$1" _tok _nl=$'\n'
  local _toks="${TRIGGER_TOKENS// /$_nl}"
  while IFS= read -r _tok; do
    [ -n "$_tok" ] || continue
    case "$_input" in *"$_tok"*) return 0 ;; esac
  done <<< "$_toks"
  return 1
}

# Words that let a later part of a command re-enter git, the cwd or a shell.
# Text is reduced to alphanumeric words first, so `/usr/bin/git` and `(cd` match.
navori_mentions_shellish() {
  local t=" ${1//[!A-Za-z0-9_]/ } "
  case "$t" in
    *" git "*|*" cd "*|*" pushd "*|*" popd "*|*" sh "*|*" bash "*|*" zsh "*|*" dash "*|*" ksh "*) return 0 ;;
    *" env "*|*" eval "*|*" exec "*|*" command "*|*" builtin "*|*" source "*|*" xargs "*) return 0 ;;
  esac
  return 1
}

# Sets `navori_heredoc_stripped` to $1 minus the bodies (and terminators) of
# heredocs this hook may safely treat as data; the introducing line is KEPT, so
# `git commit -F - <<'EOF'` still triggers. Any doubt (second heredoc on the
# line, unterminated body, empty tag) leaves the text untouched: fail closed.
# All locals are declared once at the top: zsh prints a re-declared `local`.
navori_strip_heredoc_bodies() {
  local input="$1" line before rest seg pre pfirst tag after cmp="" out="" r=""
  local dash=0 inbody=0 tab=$'\t' nl=$'\n'
  navori_heredoc_stripped="$input"
  case "$input" in *'<<'*) ;; *) return 0 ;; esac
  while IFS= read -r line; do
    if [ "$inbody" = 1 ]; then
      cmp="$line"
      if [ "$dash" = 1 ]; then cmp="${cmp#"${cmp%%[!$tab]*}"}"; fi
      if [ "$cmp" = "$tag" ]; then inbody=0; fi
      continue
    fi
    out="$out$line$nl"
    case "$line" in *'<<'*) ;; *) continue ;; esac
    before="${line%%<<*}"
    rest="${line#*<<}"
    case "$rest" in '<'*) continue ;; esac                  # here-string: no body
    dash=0
    case "$rest" in -*) dash=1; rest="${rest#-}" ;; esac
    rest="${rest#"${rest%%[![:space:]]*}"}"
    tag=""; after=""
    case "$rest" in
      \'*) r="${rest#\'}"; case "$r" in *\'*) tag="${r%%\'*}"; after="${r#*\'}" ;; esac ;;
      \"*) r="${rest#\"}"; case "$r" in *\"*) tag="${r%%\"*}"; after="${r#*\"}" ;; esac ;;
      \\*) r="${rest#\\}"; tag="${r%%[!A-Za-z0-9_.-]*}"; after="${r#"$tag"}" ;;
      *) tag="${rest%%[!A-Za-z0-9_.-]*}"; after="${rest#"$tag"}" ;;
    esac
    [ -n "$tag" ] || continue
    # Nothing chained after the tag, and no second heredoc on the line.
    case "$after" in *'|'*|*';'*|*'&'*|*'<<'*) continue ;; esac
    # The word before `<<` must be `cat`. Inside `$(…)`/backticks the command
    # that receives cat's output must be a known data consumer, not an
    # interpreter (`bash -c "$(cat <<EOF`, `eval "$(cat <<EOF`).
    seg="$before"
    case "$before" in
      *'$('*) seg="${before##*\$\(}"; pre="${before%\$\(*}" ;;
      *'`'*) seg="${before##*\`}"; pre="${before%\`*}" ;;
      *) pre="" ;;
    esac
    if [ -n "$pre" ]; then
      pre="${pre##*&&}"; pre="${pre##*;}"; pre="${pre##*|}"
      pre="${pre#"${pre%%[![:space:]]*}"}"
      pfirst="${pre%%[[:space:]]*}"
      case "$pfirst" in gh|git|echo|printf) ;; *) continue ;; esac
    fi
    seg="${seg#"${seg%%[![:space:]]*}"}"
    case "$seg" in *'|'*|*';'*|*'&'*) continue ;; esac
    case "$seg" in cat|cat[[:space:]]*) ;; *) continue ;; esac
    inbody=1
  done <<< "$input"
  [ "$inbody" = 0 ] || return 0                             # unterminated: keep all
  navori_heredoc_stripped="$out"
  return 0
}

# Counts the segments of $1 that start with a gated op ($TRIGGER_RE); sets the
# global `navori_trigger_hits`. `$2` = 1 stops at the first hit (is_scan_trigger
# only needs "any"). The single home of the segment normalisation, shared with
# navori_commit_landing so the two can never disagree about what a segment is.
navori_count_triggers() {
  # Pre-expanded newline: zsh does NOT expand $'\n' in the REPLACEMENT of
  # ${var//pat/repl} (it inserts the literal characters), so an inline $'\n'
  # left compound commands unsplit there and the gate silently skipped
  # `cd x && git commit` (#391). A plain variable expands identically in
  # bash and zsh. ($'\n' in PATTERN position expands fine in both.)
  local input="$1" stop="${2:-0}" segment nl=$'\n'
  navori_trigger_hits=0
  if [ "${TRIGGER_STRIP_HEREDOC_BODIES:-}" = 1 ]; then
    case "$input" in *'<<'*) navori_strip_heredoc_bodies "$input"; input="$navori_heredoc_stripped" ;; esac
  fi
  # FIX B: join `\<newline>` continuations into a space FIRST, so a command
  # split across lines with a trailing backslash stays ONE logical segment
  # (otherwise the subcommand/flag lands in a segment not starting with git).
  input="${input//\\$'\n'/ }"
  input="${input//&&/$nl}"
  input="${input//||/$nl}"
  input="${input//;/$nl}"
  input="${input//|/$nl}"
  # `<<<` feeds the already-expanded value as data — no re-evaluation — so a
  # command that contains backticks/$() is inspected, never executed.
  while IFS= read -r segment; do
    segment="${segment#"${segment%%[![:space:]]*}"}"        # strip leading ws
    # FIX C: peel wrappers so `(git …`, `\git`, `command git …` and
    # `VAR=val git …` all reduce to a plain `git …` before matching.
    while [[ "$segment" == \(* ]]; do                       # strip leading ( runs
      segment="${segment#\(}"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    done
    segment="${segment#\\}"                                 # strip a leading backslash (\git)
    while [[ "$segment" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do  # strip VAR=val prefixes
      case "$segment" in
        *[[:space:]]*)
          segment="${segment#*[[:space:]]}"
          segment="${segment#"${segment%%[![:space:]]*}"}"
          ;;
        *) segment=""; break ;;
      esac
    done
    if [[ "$segment" == command\ * ]]; then                 # strip a leading `command ` word
      segment="${segment#command }"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    fi
    # FIX C: allow git global options between `git` and the subcommand
    # (`git -c k=v commit`, `git -C /repo push`). $TRIGGER_RE's trailing boundary
    # keeps `git commitgraph` / `git config …` from matching.
    if printf '%s' "$segment" | grep -qE "$TRIGGER_RE"; then
      navori_trigger_hits=$((navori_trigger_hits + 1))
      if [ "$stop" = 1 ]; then return 0; fi
    fi
  done <<< "$input"
  return 0
}

is_scan_trigger() {
  # ─── Fast path (spec 0016 T3.2, second pass): the segment loop pays one
  # `grep -qE` FORK per segment — and a heredoc body or a 40-step compound
  # is 40 segments, so the field cost scaled with command length (measured:
  # 2.8 ms trivial, 14.8 ms for a 199-char heredoc, 95.8 ms for 40 segments;
  # p50 across one real session's commands was 40 ms per hook, not the
  # trivial floor). No $TRIGGER_RE can match without one of the caller's
  # literal TOKENS appearing in the segment it matches — and every segment is
  # a substring of the input, transformed only by insertions (`\<NL>` → space,
  # separators → newline) and prefix-peeling, none of which can CREATE a
  # token. So a single in-process substring scan of the raw input is a strict
  # superset of the segment matches: if no token is present, no segment can
  # match, and the gate answers "not for me" without a single fork. Same
  # argument, same safe direction, as the guard's own fast path.
  #
  # $TRIGGER_TOKENS is set by the including hook NEXT TO its $TRIGGER_RE, so
  # the pair travels together; when unset the fast path disarms and the loop
  # runs exactly as before (fail-open to the SLOW path, never to a skip).
  has_trigger_token "$1" || return 1
  navori_count_triggers "$1" 1
  [ "$navori_trigger_hits" -gt 0 ]
}

# Resolution of the working tree the commit acts on (#454). Shared body; defines
# `navori_worktree` but resolves nothing until it is called, so a Bash call that
# is not a commit still pays nothing for it.
# Shared worktree resolver — inlined into each gate hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Requires the
# `extract-cmd` partial to have run first ($payload and $cmd in scope).
#
# WHY (#454): settings.json invokes these hooks as
# `bash "$CLAUDE_PROJECT_DIR/.claude/scripts/check-semgrep.sh"`, so the hook
# PROCESS starts in the MAIN repo even when the commit happens inside an agent
# worktree under `.claude/worktrees/`. The old `cd "$(git rev-parse
# --show-toplevel)"` therefore resolved the main repo — whose tree is clean — so
# `git diff --name-only main` returned 0 files and the gate exited 0. Not a false
# negative from the scanner: the scanner never ran. A `cd` to an arbitrary tree
# is exactly the bug, so nothing below ever guesses: every candidate must prove
# it is a git working tree, or the next one is tried — and the one the COMMAND
# names must additionally prove it is part of the repository being protected
# (see the same-repository constraint in `navori_worktree`).
#
# `navori_worktree` prints the absolute root of the working tree the gated git
# command will act on, or nothing when none resolves. It is a FUNCTION, not a
# top-level assignment, because `quality-gate-pre-commit` inlines this partial on
# a path that runs on EVERY Bash tool call: callers pay the git/jq probes only
# after their own trigger matched.

# First shell token of $1: a leading single/double-quoted string (so a path with
# spaces survives) or an unquoted run of non-space characters.
navori_first_token() {
  local s="$1"
  case "$s" in
    \"*) s="${s#\"}"; printf '%s' "${s%%\"*}" ;;
    \'*) s="${s#\'}"; printf '%s' "${s%%\'*}" ;;
    *) printf '%s' "${s%%[[:space:]]*}" ;;
  esac
}

# Directory named by the command itself, if any. Two shapes, both real in this
# harness: `git -C <dir> commit …` (git names its own tree) and
# `cd <dir> && git commit …` (how an agent commits into its worktree from a
# session anchored elsewhere). Prints the raw token; the caller resolves it.
#
# TODO(scope): only the FIRST segment is inspected for `cd`. A `cd` buried
# mid-chain (`pnpm build && cd sub && git commit`) falls through to the payload
# cwd, which is right whenever that `cd` stays inside the same repo. Walk the
# segments if a real command shows up where it does not.
navori_cmd_dir() {
  local text="$1" rest="" head=""
  case "$text" in
    *"git -C "*)
      rest="${text#*git -C }"
      ;;
    *)
      head="${text%%&&*}"
      head="${head#"${head%%[![:space:]]*}"}"
      case "$head" in
        "cd "*) rest="${head#cd }" ;;
      esac
      ;;
  esac
  [ -n "$rest" ] || return 1
  rest="${rest#"${rest%%[![:space:]]*}"}"
  # A token that needs the shell to expand it ($VAR, `sub`, ~, globs) is NOT
  # resolved here: guessing wrong points the scan at the wrong tree, which is
  # the very failure this partial exists to kill. Ignoring it just falls through
  # to the next candidate.
  case "$rest" in
    ""|*'$'*|*'`'*|*'*'*|*'?'*|"~"*) return 1 ;;
  esac
  navori_first_token "$rest"
}

# Absolute, symlink-resolved path of a working tree's SHARED git dir, or nothing
# when $1 is not inside a git working tree. `--git-common-dir` names the `.git`
# of the MAIN checkout, so every linked worktree of one repository — and every
# subdirectory of it — reports the SAME value, while a different repository
# reports its own and a submodule reports `<main>/.git/modules/<name>`. That
# makes it an identity test for "same repository", which `--show-toplevel` (one
# per working tree) and `--git-dir` (one per worktree) are not.
navori_repo_id() {
  local dir="$1" common=""
  common=$(git -C "$dir" rev-parse --git-common-dir 2>/dev/null) || return 1
  [ -n "$common" ] || return 1
  # `git -C <dir>` chdirs to <dir> first, so a relative answer (`.git`,
  # `../../.git`) is relative to <dir>. `pwd -P` canonicalises both sides the
  # same way, which also settles macOS's /var vs /private/var symlink.
  (cd "$dir" && cd "$common" && pwd -P) 2>/dev/null
}

# First argument that resolves to a git working tree; prints its root.
navori_first_tree() {
  local candidate toplevel
  for candidate in "$@"; do
    [ -n "$candidate" ] || continue
    [ -d "$candidate" ] || continue
    toplevel=$(git -C "$candidate" rev-parse --show-toplevel 2>/dev/null) || continue
    [ -n "$toplevel" ] || continue
    printf '%s' "$toplevel"
    return 0
  done
  return 1
}

# Hook's own path, captured HERE at the partial's top level (every consumer inlines
# it at script top level). NEVER read `$0` inside a `navori_*` function: zsh sets it
# to the function's name there (FUNCTION_ARGZERO). Used only as a string, never
# resolved. A relative path is anchored on the hook's cwd, where the shell found it.
navori_hook_path="$0"
case "$navori_hook_path" in /*) ;; *) navori_hook_path="$PWD/$navori_hook_path" ;; esac
navori_home_id=""
navori_home_done=0

# HOME repository (#1099): the repo this hook protects, as a repo id in
# `navori_home_id` (empty = unknown). Known only if ALL hold:
#   - `CLAUDE_PROJECT_DIR` is non-empty;
#   - the hook's own path is exactly `${CLAUDE_PROJECT_DIR%/}/.claude/hooks/<file>`
#     or `.../.claude/scripts/<file>` (how settings.json registers it). A bare
#     prefix is not enough: a leaked variable plus a hook of a repo NESTED under it
#     would make the outer repo "home" and skip every gate of the inner one. `.codex/`
#     never qualifies, so a Codex hook is always home-unknown;
#   - that directory resolves to a repo id.
# Any doubt means unknown, and unknown never produces `foreign` without a `cd`/`-C`
# in the command. Memoised: the callers pay the git fork once. Sets a global (no
# subshell); declares locals once at the top (zsh prints a re-declared `local`).
navori_home_resolve() {
  local cpd rest file
  [ "$navori_home_done" = 0 ] || return 0
  navori_home_done=1
  cpd="${CLAUDE_PROJECT_DIR:-}"
  [ -n "$cpd" ] || return 0
  cpd="${cpd%/}"
  case "$navori_hook_path" in
    "$cpd"/*) rest="${navori_hook_path#"$cpd"/}" ;;
    *) return 0 ;;
  esac
  case "$rest" in
    .claude/hooks/*|.claude/scripts/*) file="${rest#.claude/*/}" ;;
    *) return 0 ;;
  esac
  case "$file" in ""|.|..|*/*) return 0 ;; esac
  navori_home_id=$(navori_repo_id "$CLAUDE_PROJECT_DIR" || true)
  return 0
}

# Resolution, most specific first:
#   1. the directory the command names (`git -C` / a leading `cd`), ONLY when it
#      belongs to the same repository as the anchor (see the constraint below);
#   2. the payload's `.cwd` — Claude Code sends the CURRENT working directory of
#      the tool call, a documented field distinct from $CLAUDE_PROJECT_DIR (the
#      project root). In an agent worktree these differ; that gap IS #454;
#   3. the hook process's own cwd — the pre-#454 behaviour, still correct for a
#      plain terminal or git-hook invocation.
navori_worktree() {
  local payload_cwd anchor named anchor_repo="" named_repo=""
  payload_cwd=$(payload_field cwd)
  # A relative `cd sub` resolves against the shell's cwd, which is the payload's
  # when Claude Code sends one and the hook process's otherwise.
  anchor="$payload_cwd"
  [ -d "$anchor" ] || anchor="$PWD"
  named=$(navori_cmd_dir "$cmd" || true)
  case "$named" in
    "") ;;
    /*) ;;
    *) named="$anchor/$named" ;;
  esac
  # SAME-REPOSITORY CONSTRAINT — DO NOT REMOVE (#454, review finding).
  # Candidate 1 is the only one the COMMAND controls, and it is tried first, so
  # accepting any git tree it happens to name lets that command OVERRIDE the
  # trustworthy candidates below it: `git -C <other-repo> log && git commit`,
  # `cd <other> && cd <wt> && git commit`, `cd <sub> && cd .. && git commit`, or
  # merely the bytes `git -C <path>` inside a commit MESSAGE, all aimed the scan
  # at a foreign tree with nothing to scan — exit 0 with the scanner never run,
  # which is the very failure #454 is about (and, for a commit in the main repo,
  # strictly worse than not resolving worktrees at all).
  # So a directory the command names is accepted only when it is part of the
  # repository the hook is protecting, i.e. the anchor's. Linked worktrees share
  # the main checkout's git dir, so every legitimate agent worktree passes; a
  # different repository and a submodule (its own git dir under
  # `<main>/.git/modules/`) do not, and fall through to the payload cwd — the
  # stricter direction. An unresolvable anchor drops candidate 1 for the same
  # reason: nothing to check it against — unless the named dir IS the hook's home
  # repo (#1099: the session sits in another repo but the command names the
  # protected one), which only ever moves the scan toward the protected repo.
  # Ceiling: two linked worktrees of the SAME repository are indistinguishable
  # this way, so naming a sibling worktree still beats the payload cwd. Both are
  # trees of the repo being protected, so the scan stays inside it. Walk the
  # segments to the one that actually carries the `git commit` if a real command
  # shows up where that is not enough.
  if [ -n "$named" ]; then
    anchor_repo=$(navori_repo_id "$anchor" || true)
    named_repo=$(navori_repo_id "$named" || true)
    navori_home_resolve
    if [ -z "$named_repo" ] || { [ "$named_repo" != "$anchor_repo" ] && [ "$named_repo" != "$navori_home_id" ]; }; then
      named=""
    fi
  fi
  navori_first_tree "$named" "$payload_cwd" "$PWD" || true
}

# ─── Where does the commit LAND? (#1095) ────────────────────────────────────────
# `navori_worktree` above answers "which tree do I scan"; this answers "is the
# commit even for the repository this gate protects". A commit that provably
# lands in ANOTHER repository (`cd <other> && git commit`, `git -C <other>
# commit`) must not be gated against the anchor's tree: that tree holds none of
# the diff. Classification is a POSITIVE grammar with a deny-list of ambiguity —
# `foreign` only when every step to the commit has a certain cwd effect and the
# resolved repository really differs; the commit message is never read (#454:
# `git commit -m "use git -C <other>"` lands in the anchor). Anything unsure is
# `ambiguous`, which callers treat exactly like `same-repo`: run the gate.
#
# Requires the `gate-trigger` partial (navori_count_triggers, $TRIGGER_RE) and
# `extract-cmd` (payload_field). Always returns 0 and sets, without a subshell:
#   navori_landing       same-repo | foreign | ambiguous
#   navori_landing_root  landing toplevel (foreign only)
# "foreign" means the command's landing repo differs from the repository this hook
# protects (#1099). With no `cd`/`-C` the landing dir IS the payload cwd, so a
# session anchored in another repo is foreign too. The protected repo is the HOME
# id (`navori_home_resolve`); when home is unknown the comparison degrades to the
# #1095 rule (payload-cwd repo, widened by the raw `CLAUDE_PROJECT_DIR` repo, which
# can only turn `foreign` into `same-repo`) and a command without `cd`/`-C` is
# `same-repo` with no fork. "commit" below means the one gated op.
#
# The gated op (#1098) is whatever the caller's $TRIGGER_RE counts: `git commit`
# for QG and jscpd, plus `git push` and `gh pr create` for semgrep. The walk
# matches that same regex, so there is no second copy to drift. `gh pr create`
# lands in the cwd's repo unless it names another one (`-R`/`--repo`/`GH_REPO`),
# which is `ambiguous` (the scan runs).
#
# A chain of gated ops joined by `&&` (#1115) is classified per op, each with its
# own `-C` (and the one leading `cd`): `foreign` only when EVERY op lands in the
# same foreign toplevel and the walk saw every op the counter did (a hidden op
# behind `;`, `|`, `||` or a wrapper makes hits > found). One op in the home repo,
# two toplevels (even two worktrees of one repo) or an unproven op is `ambiguous`.
# After the first gated op only read-only `git` segments (status|diff|log|show|
# rev-parse|push, no global options) and echo|printf|true|:|ls|pwd may follow: the
# counter cannot see a `-C "dir with spaces"` value, an alias or an exec-capable
# subcommand, so any other tail (an `export GIT_DIR`, a later `cd`, a shell) is
# `ambiguous`. QG/jscpd do not gate `push`, so for them `commit(F) && git push`
# is foreign while semgrep, which counts both ops, decides on both.

# Reads one shell token off the front of $1 into `navori_tok` / `navori_rest`.
# Returns 1 for anything the shell would expand or that is malformed, so the
# caller falls back to `ambiguous`.
navori_take_token() {
  local s="$1" nl=$'\n'
  navori_tok=""; navori_rest=""
  s="${s#"${s%%[![:space:]]*}"}"
  case "$s" in
    \'*)
      s="${s#\'}"
      case "$s" in *\'*) ;; *) return 1 ;; esac
      navori_tok="${s%%\'*}"; navori_rest="${s#*\'}"
      case "$navori_rest" in ""|[[:space:]]*) ;; *) return 1 ;; esac
      ;;
    \"*)
      s="${s#\"}"
      case "$s" in *\"*) ;; *) return 1 ;; esac
      navori_tok="${s%%\"*}"; navori_rest="${s#*\"}"
      case "$navori_rest" in ""|[[:space:]]*) ;; *) return 1 ;; esac
      ;;
    *)
      navori_tok="${s%%[[:space:]]*}"; navori_rest="${s#"$navori_tok"}"
      case "$navori_tok" in
        *';'*|*'|'*|*'&'*|*'<'*|*'>'*|*'('*|*')'*|*"'"*|*'"'*) return 1 ;;
      esac
      ;;
  esac
  case "$navori_tok" in
    ""|'~'*|*'$'*|*'`'*|*'\'*|*'*'*|*'?'*|*'['*|*'{'*|*"$nl"*) return 1 ;;
  esac
  return 0
}

# Where does ONE gated op land? Takes the op's `cd` target and `-C` target (either
# may be empty) and sets, without a subshell:
#   navori_op_kind  same | foreign | "" (unproven)
#   navori_op_top   landing toplevel (foreign only)
# Every unproven path returns with the empty kind.
navori_op_landing() {
  local cd_dir="$1" c_dir="$2" pcwd base dir rel=0 top sub id_l id_a id_h nl=$'\n'
  navori_op_kind=""; navori_op_top=""

  # No cd/-C: the landing dir is the payload cwd. Without a PROVEN home there is
  # nothing to compare it with, so today's answer (and zero forks) stands.
  if [ -z "$cd_dir" ] && [ -z "$c_dir" ]; then
    navori_home_resolve
    if [ -z "$navori_home_id" ]; then navori_op_kind="same"; return 0; fi
  else
    navori_home_resolve
  fi

  pcwd=$(payload_field cwd)
  base="$pcwd"
  [ -d "$base" ] || base="$PWD"
  dir="$base"
  if [ -n "$cd_dir" ]; then
    case "$cd_dir" in
      /*) dir="$cd_dir" ;;
      *)
        rel=1; dir="$base/$cd_dir"
        # A non-empty CDPATH can make `cd <relative>` land somewhere else.
        [ -z "${CDPATH:-}" ] || return 0
        ;;
    esac
  fi
  if [ -n "$c_dir" ]; then
    case "$c_dir" in
      /*) dir="$c_dir"; rel=0 ;;
      *) rel=1; dir="$dir/$c_dir" ;;
    esac
  fi
  # `..` in a relative path resolves logically in the shell but physically in
  # the kernel; they differ when the base itself sits behind a symlink.
  if [ "$rel" = 1 ]; then
    case "$cd_dir$nl$c_dir" in
      *'..'*) [ "$(cd "$base" 2>/dev/null && pwd -P)" = "$base" ] || return 0 ;;
    esac
  fi

  [ -d "$dir" ] || return 0
  top=$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null) || return 0
  [ -n "$top" ] || return 0
  # A submodule target (or cwd) is deliberately not `foreign` (its commit is part
  # of the superproject's work): the anchor's gate runs.
  sub=$(git -C "$dir" rev-parse --show-superproject-working-tree 2>/dev/null) || return 0
  [ -z "$sub" ] || return 0
  id_l=$(navori_repo_id "$dir" || true)
  [ -n "$id_l" ] || return 0
  if [ -n "$navori_home_id" ]; then
    # Proven home: the one definition of foreign.
    if [ "$id_l" = "$navori_home_id" ]; then
      navori_op_kind="same"
    else
      navori_op_kind="foreign"; navori_op_top="$top"
    fi
    return 0
  fi
  # Home unknown: the #1095 rule.
  id_a=$(navori_repo_id "$base" || true)
  [ -n "$id_a" ] || return 0
  id_h=""
  if [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then
    id_h=$(navori_repo_id "$CLAUDE_PROJECT_DIR" || true)
  fi
  if [ "$id_l" = "$id_a" ] || { [ -n "$id_h" ] && [ "$id_l" = "$id_h" ]; }; then
    navori_op_kind="same"
  else
    navori_op_kind="foreign"; navori_op_top="$top"
  fi
  return 0
}

# Parses the target of ONE gated segment ($1 = its first line, $2 = the whole
# segment) and sets `navori_op_cdir` to the op's `-C` target ("" when none).
# Returns 1 for anything the parser will not follow.
navori_op_target() {
  local first="$1" seg="$2" p arg nc=0
  navori_op_cdir=""
  case "$first" in
  gh[[:space:]]*)
    # `gh pr create`: no global -C, so it lands where the cwd (or the `cd`) is —
    # unless it names another repo, which the parser will not follow. Any `-R` or
    # `--repo` anywhere in the segment (message text included) reads as ambiguous.
    p="${first#gh}"
    navori_take_token "$p" || return 1
    [ "$navori_tok" = pr ] || return 1
    navori_take_token "$navori_rest" || return 1
    [ "$navori_tok" = create ] || return 1
    case "$seg" in *'-R'*|*'--repo'*) return 1 ;; esac
    [ -z "${GH_REPO:-}" ] || return 1
    return 0
    ;;
  esac
  # The segment's own git global options, positionally. Text after `commit`/
  # `push` (the message) is never read.
  p="${first#git}"
  while :; do
    navori_take_token "$p" || return 1
    arg="$navori_tok"; p="$navori_rest"
    case "$arg" in
      commit|push) return 0 ;;
      -C)
        [ "$nc" = 0 ] || return 1
        nc=1
        navori_take_token "$p" || return 1
        navori_op_cdir="$navori_tok"; p="$navori_rest"
        ;;
      -c) navori_take_token "$p" || return 1; p="$navori_rest" ;;
      --no-pager|-p|--paginate|-P|--no-optional-locks|--literal-pathspecs|--glob-pathspecs|--noglob-pathspecs|--icase-pathspecs|--no-replace-objects) ;;
      *) return 1 ;;
    esac
  done
}

navori_commit_landing() {
  local c rest seg first tailtxt gated w sub line ops="" acc="" acc_top="" prev_c="" n_done=0
  local cd_dir="" found=0 more=1 cdcount=0 nl=$'\n' tab=$'\t'
  navori_landing="ambiguous"; navori_landing_root=""

  navori_count_triggers "$1" 0
  [ "$navori_trigger_hits" -ge 1 ] || return 0

  navori_strip_heredoc_bodies "$1"
  c="$navori_heredoc_stripped"
  c="${c//\\$'\n'/ }"
  # The heredoc strip leaves a trailing newline on the last segment.
  c="${c%"${c##*[![:space:]]}"}"

  # Phase 1 — walk the `&&` chain without forking git. Before the first gated op:
  # at most one `cd <literal>` and neutral `git …` segments. Each gated op is
  # recorded with its own `-C`. After it, only a fixed allowlist of segments that
  # can neither move the cwd or env nor commit; anything else is ambiguous.
  rest="$c"
  while [ "$more" = 1 ]; do
    case "$rest" in
      *'&&'*) seg="${rest%%&&*}"; rest="${rest#*&&}" ;;
      *) seg="$rest"; rest=""; more=0 ;;
    esac
    seg="${seg#"${seg%%[![:space:]]*}"}"
    first="${seg%%"$nl"*}"
    gated=0
    case "$first" in
      git[[:space:]]*|gh[[:space:]]*)
        if printf '%s' "$first" | grep -qE "$TRIGGER_RE"; then gated=1; fi
        ;;
    esac
    if [ "$gated" = 1 ]; then
      navori_op_target "$first" "$seg" || return 0
      ops="${ops}o${navori_op_cdir}${nl}"
      found=$((found + 1))
      # Anything on this op's own line after `;`/`|`/`&`, or on later lines, could
      # re-enter git, cd or a shell (a second, uncounted commit landing elsewhere).
      tailtxt="${seg#"$first"}$nl"
      case "$first" in *';'*|*'|'*|*'&'*) tailtxt="${first#*[;|&]}$nl$tailtxt" ;; esac
      if navori_mentions_shellish "$tailtxt"; then return 0; fi
      continue
    fi
    case "$seg" in *"$nl"*) return 0 ;; esac
    seg="${seg%"${seg##*[![:space:]]}"}"
    if [ "$found" = 0 ]; then
      case "$seg" in
        cd[[:space:]]*)
          [ "$cdcount" = 0 ] || return 0
          cdcount=1
          navori_take_token "${seg#cd}" || return 0
          case "$navori_rest" in *[![:space:]]*) return 0 ;; esac
          cd_dir="$navori_tok"
          case "$cd_dir" in -*) return 0 ;; esac
          ;;
        git[[:space:]]*)
          case "$seg" in
            *';'*|*'|'*|*'&'*|*'<'*|*'>'*|*'('*|*')'*|*'$'*|*'`'*) return 0 ;;
          esac
          ;;
        *) return 0 ;;
      esac
      continue
    fi
    # After a gated op. No metacharacter, expansion or escape in any tail segment.
    case "$seg" in
      *';'*|*'|'*|*'&'*|*'<'*|*'>'*|*'('*|*')'*|*'$'*|*'`'*|*'\'*|*"$tab"*) return 0 ;;
    esac
    case "$seg" in
      git\ *)
        # Read-only subcommands, single spaces, no global options (`-C`, `-c`,
        # `--git-dir` …): an alias, an exec-capable subcommand or another repo
        # target is invisible to the counter, so it is ambiguous.
        case "$seg" in *'--exec'*|*'--receive-pack'*|*'--upload-pack'*|*'--config-env'*) return 0 ;; esac
        sub="${seg#git }"; sub="${sub%% *}"
        case "$sub" in status|diff|log|show|rev-parse|push) ;; *) return 0 ;; esac
        ;;
      *)
        w="${seg%%[[:space:]]*}"
        case "$w" in echo|printf|true|:|ls|pwd) ;; *) return 0 ;; esac
        ;;
    esac
  done
  # Every gated op the counter saw must be an op the walk parsed (INV: a hidden
  # op behind `;`, `|`, `||`, a subshell or a wrapper makes hits > found).
  [ "$found" -ge 1 ] || return 0
  [ "$found" = "$navori_trigger_hits" ] || return 0

  # Phase 2 — resolve each op with its own `-C` and fold unanimously: `foreign`
  # only when every op lands in the SAME foreign toplevel; any op in the home
  # repo, in a different toplevel or unproven leaves the verdict ambiguous.
  while IFS= read -r line; do
    case "$line" in o*) ;; *) continue ;; esac
    if [ "$n_done" = 0 ] || [ "${line#o}" != "$prev_c" ]; then
      navori_op_landing "$cd_dir" "${line#o}"
      prev_c="${line#o}"; n_done=1
    fi
    case "$navori_op_kind" in
      same) [ "$acc" != foreign ] || return 0; acc="same" ;;
      foreign)
        [ "$acc" != same ] || return 0
        if [ "$acc" = foreign ] && [ "$navori_op_top" != "$acc_top" ]; then return 0; fi
        acc="foreign"; acc_top="$navori_op_top"
        ;;
      *) return 0 ;;
    esac
  done <<< "$ops"
  case "$acc" in
    same) navori_landing="same-repo" ;;
    foreign) navori_landing="foreign"; navori_landing_root="$acc_top" ;;
  esac
  return 0
}

# An EMPTY `$cmd` is not "some command that isn't a commit": it means nothing
# could be read out of the tool input at all (no JSON parser, a malformed or
# truncated payload). `is_scan_trigger ""` simply finds no git segment, so the
# whole block below was skipped WITHOUT A WORD — a gate that omits itself in
# silence is indistinguishable from a gate that passed (#511). Its two siblings
# (`check-semgrep.sh`, `check-jscpd.sh`) already scan unconditionally there,
# which is the contract the shared extractor documents; this one drifted. The
# verdict is now stated out loud in both directions, per #88.
run_needed=0
if [ -z "$cmd" ]; then
  echo "[navori] no command could be read from the tool input; running the quality gate anyway rather than skipping it silently." >&2
  run_needed=1
elif is_scan_trigger "$cmd"; then
  run_needed=1
fi

# A commit that provably lands in ANOTHER repository (#1095) is not this gate's
# business: its tree holds none of the diff. Ambiguous shapes fall through and
# run the gate (fail closed, #454). The empty-$cmd path above never gets here.
if [ "$run_needed" = 1 ] && [ -n "$cmd" ]; then
  navori_commit_landing "$cmd"
  if [ "$navori_landing" = foreign ]; then
    navori_audit_skip_reason="el commit va a otro repositorio ($navori_landing_root); el gate de este repo no aplica"
    echo "[navori] quality-gate NOT run: this commit lands in another repository ($navori_landing_root), not the one this hook protects. That repository's own gate is not run from here." >&2
    # Detect, never run: the destination's config is data. File existence plus a
    # jq type check only; without jq (or on invalid JSON) this degrades to the
    # message above, never to a failure.
    if [ -f "$navori_landing_root/navori.config.json" ] && command -v jq >/dev/null 2>&1 \
      && jq -e '(.qualityGate.fast | type) == "string" and (.qualityGate.fast | length) > 0' "$navori_landing_root/navori.config.json" >/dev/null 2>&1; then
      navori_audit_skip_reason="el commit va a otro repositorio ($navori_landing_root); su qualityGate.fast propio NO se ejecuto"
      echo "[navori] The destination repository declares its own qualityGate.fast in navori.config.json; it was NOT executed. Run it there before relying on this commit." >&2
    fi
    exit 0
  fi
fi

if [ "$run_needed" = 1 ]; then
  # Pin the cwd to the root of the tree BEING COMMITTED before anything below
  # runs. Claude Code fires PreToolUse hooks from a cwd that is neither always
  # the repo root (#309: a relative gate like `cd packages/cli && pnpm lint`
  # fails from a subdir) nor always the right repo (#454: it is the MAIN repo
  # even when the commit happens in an agent worktree, so the gate validated a
  # tree that did not hold the diff).
  # `nv_project_dir` stays as a fallback for the no-git case (spec 0035 D2:
  # $CLAUDE_PROJECT_DIR under Claude, the payload cwd's git toplevel under
  # Codex); when nothing resolves the substitution is empty and `cd ""` is a
  # no-op, so behavior outside a repo is unchanged.
  gate_root=$(navori_worktree)
  cd "${gate_root:-${nv_project_dir:-}}" || exit 2
  # qualityGate.fast is shell-quoted at render time via the shq: marker (#197).
  # The gate string is still `eval`'d by run_gate below (running the gate is the
  # feature), but quoting it here means a hostile qualityGate.fast survives as one
  # literal token instead of injecting commands at variable-assignment time.
  gate='ruff check .'
  gate_bin="${gate%% *}"
  if command -v "$gate_bin" >/dev/null 2>&1; then
    run_gate "$gate"
  else
    # The declared runner isn't on PATH. If it's a package manager, detect the
    # repo's real one from lockfiles and retry through it (a `pnpm run x` gate
    # still runs in a bun-only checkout). #88: NEVER skip the gate silently —
    # when nothing can run it, BLOCK the commit loudly instead of the old
    # `exit 0` that handed a contributor zero quality gate without a word.
    detected_pm="$(detect_pm)"
    if is_pm "$gate_bin" && [ -n "$detected_pm" ] && [ "$detected_pm" != "$gate_bin" ] && command -v "$detected_pm" >/dev/null 2>&1; then
      echo "[navori] '$gate_bin' is not on PATH; using the lockfile-detected package manager: '$detected_pm'." >&2
      run_gate "$detected_pm ${gate#* }"
    else
      echo "[navori] quality-gate NOT run: '$gate_bin' is not on PATH and no alternative package manager was detected that could run it." >&2
      # No verdict, the TOOL is missing (#1117). Under a Claude PreToolUse hook
      # the user decides; anywhere else (Codex drops `ask`, no payload) the
      # commit stays BLOCKED rather than skipping the gate silently (#88).
      # The explicit engine test is the static proof (hook-claims-vs-scripts) that
      # the Codex path differs; `navori_can_ask` re-checks it with the payload.
      if [ "$nv_engine" = codex ] || ! navori_can_ask; then
        echo "[navori] Commit BLOCKED to avoid skipping the gate silently. Install '$gate_bin', or if you really want to skip it run the commit yourself outside the agent." >&2
        exit 2
      fi
      navori_audit_ask_reason="quality gate sin veredicto: '$gate_bin' no esta en PATH y no hay gestor alterno"
      jq -cn --arg reason "[navori] The quality gate did not run: '$gate_bin' (from qualityGate.fast) is not on PATH and no lockfile-detected package manager could run it, so there is no verdict. Approve to commit WITHOUT the quality gate, or deny and install '$gate_bin'." '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"ask",permissionDecisionReason:$reason}}'
      exit 0
    fi
  fi
fi
# navori:managed end id="qg-pre-commit-base"

# user: add extra checks here. `$cmd` is already parsed from the tool input.
# Example:
#
#   case "$cmd" in
#     'git push'*)
#       bash scripts/check-licenses.sh || exit 2
#       ;;
#   esac
#
# Use a path your own repo owns. The example used to point at a plugin script
# under `.claude/scripts/`, which only exists when that plugin is installed AND
# the engine is Claude — copied verbatim it fails under Codex (#389).
