# navori:managed start id="qg-pre-commit-base" hash="c4443dbb" version="0.10.0" source="@navori/core"
#!/usr/bin/env bash
#
# Pre-commit / pre-push quality gate hook.
# Reads the tool input (from Claude Code's PreToolUse Bash matcher) and runs
# the project's `qualityGate.fast` command before allowing the commit.
#
# It does NOT verify the reviewer's content receipt. That backstop lived here
# until #365 and was removed on purpose: five fail-open paths (worktree, Codex
# workspace, zsh word-splitting, non-ASCII paths, a truncated singleton receipt)
# against zero documented catches, and one of its failure modes blocked every
# PR in the repo. The receipt is a handoff between the `reviewer` and the
# `publisher`, which verifies it agent-side and re-signs the delta. Don't
# re-add the check here without a captured case it would have caught.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand. Add your repo-specific checks in the user section at the
# bottom — they keep `cmd` and the original exit codes in scope.
set -euo pipefail

# Command extraction (payload → $cmd). Shared body, single source of truth.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.
cmd=$(extract_cmd)

navori_audit_name="quality-gate-pre-commit"
navori_audit_phase="PreToolUse"
navori_audit_tool="Bash"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# They exist because this hook is FAIL-OPEN: if the file ever runs WITHOUT its
# includes expanded — a raw copy of the asset, a render that half-finished — an
# undefined function would be exit 127, and under `set -e` that KILLS the hook.
# A recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/render/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  # The third field is the OWNER, and it is never empty: inside a subagent the
  # host sends a real `agent_id`; on the main thread it sends none and the
  # literal below names the orchestrator explicitly.
  #
  # It used to be `// ""`, and the empty case did not stay empty — it came out
  # as the `cwd`. Command substitution strips trailing newlines, so an empty
  # third field left `$navori_audit_fields` with only two lines; then
  # `${rest#*<NL>}` found no newline in `"cwd"` and POSIX says a `#` pattern
  # that does not match returns the string UNCHANGED. 41,581 of the park's
  # 52,460 recorded owners (79%) were a filesystem path for that reason.
  #
  # The consumer's behaviour does not change — `ownerOf` looks the value up
  # among the session's agents and sends anything that names nobody to the
  # orchestrator, which is where a path already went — but the record stops
  # claiming the repo directory is an agent. Old logs keep working through the
  # same "names nobody" branch.
  #
  # The trailing "." is a sentinel, not data: with it the third field is always
  # followed by a newline, so the `%%` below cannot fall into the same trap if
  # a future field is ever empty.
  #
  # The owner is picked with an explicit "first non-empty string", NOT with
  # `.agent_id // .subagent_id // "orchestrator"`. In jq only `null` and `false`
  # are falsy, so a host that sends the key with an EMPTY string satisfies `//`
  # and the chain yields `""` — the field then disappears from the record and
  # `ownerOf` falls back to the time window, which is the guess this field
  # exists to avoid. Caught by a test, not by review.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", ([.agent_id, .subagent_id] | map(select(type == "string" and . != "")) | first) // "orchestrator", .tool_use_id // "", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_tool_use_id=${navori_audit_rest%%
*}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  if [ ! -f "$navori_audit_file" ]; then
    # SPOOL for the phase that CANNOT have a log yet (#778).
    #
    # `navori audit --start` is what creates the session log, and it runs from
    # the UserPromptSubmit hook — i.e. after the first prompt. Every SessionStart
    # hook therefore fires BEFORE the file exists, and the check above threw its
    # record away every single time: measured, `session-start-context` recorded 1
    # of ~20 startups in this repo, and the only survivor was a resume onto an
    # already-open log. "Did the session load the harness?" had no witness at all,
    # which is exactly the question the recorder exists to answer.
    #
    # So those records go to a side file that `--start` absorbs. Two deliberate
    # limits keep this from becoming a leak:
    #
    #   1. SessionStart ONLY. Every other phase runs after a prompt, so a missing
    #      log there means the session is genuinely not marked — and spooling
    #      those would write four lines per Bash call, for every session of every
    #      repo, forever. That is thousands of writes to buy nothing.
    #   2. Only where the repo's audit directory ALREADY exists, which means the
    #      repo has been audited (or armed) at least once. `mkdir` is never run
    #      from here: a repo that has never used audit-mode must stay at zero
    #      files and zero forks, the same contract as the root gate above. The
    #      cost is that the FIRST audited session of a repo still loses its
    #      SessionStart records; every one after it has them.
    #
    # FAIL-OPEN, and here more than anywhere: this runs while a session is
    # opening. Every failure path below returns 0 and writes nothing to stdout —
    # a spool that could abort a hook would make observation the reason a session
    # does not start, which is the one bug this partial may never have.
    [ "${navori_audit_phase:-}" = "SessionStart" ] || return 0
    [ -d "$navori_audit_root/$navori_audit_repo" ] || return 0
    navori_audit_file=$navori_audit_root/$navori_audit_repo/pending-$navori_audit_session.jsonl
    if [ ! -e "$navori_audit_file" ]; then
      : >> "$navori_audit_file" 2>/dev/null || return 0
    fi
  fi
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  # `tsMs` is the instant at the resolution the log actually needs (#685): the
  # `ts` below truncates to the second, and 84% of a measured session's events
  # share their second with another one. This value is already computed — the
  # duration above is derived from it — so recording it costs nothing.
  #
  # Validated with the same `-ge 0` idiom as `ms`, and for the same reason: it
  # is passed as `--argjson`, so a non-numeric value would make the whole `jq`
  # fail and the event would vanish instead of merely losing a field.
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0

  # `ts` is NOT stamped here, and that is the whole point of #696: it was a
  # `date` fork per event — 46,850 of them across this store — for a string
  # fully derivable from the `tsMs` above, which `$EPOCHREALTIME` already
  # produced without spawning anything. The file's own cost doctrine (see
  # `navori_audit_now`) says spend a process only when there is no other way;
  # keeping this one made the comment lie four lines under the value that
  # refutes it.
  #
  # Nothing downstream lost a field: `parse.ts` derives the ISO from `tsMs`
  # when the record carries none, and logs written before this still have
  # theirs. The lifecycle records — `start`, `stop`, `session-end` — keep a real
  # `ts`, so a human reading the raw `.log` still has dated anchors; those are
  # ~3 per session, not one per hook.
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --arg toolUseId "${navori_audit_tool_use_id:-}" \
    --argjson ms "$navori_audit_ms" \
    --argjson tsMs "$navori_audit_end" \
    '{tsMs:$tsMs,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)
     + (if $toolUseId == "" then {} else {toolUseId:$toolUseId} end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

# This hook fires on EVERY Bash call and does real work on almost none of them,
# so its verdict is derived from the exit code in a trap rather than from a call
# per branch — the branch set here is the one most likely to grow.
#
# `navori_audit_ran_gate` is the distinction that matters: the recorded `ms` of a
# run that actually executed the gate (tens of seconds) means something very
# different from that of a run that looked at the command and moved on (single
# digits). Collapsing both into `allow` would make the timing unreadable.
navori_audit_ran_gate=0
navori_audit_on_exit() {
  navori_audit_code=$?
  # A cancelled hook reaches this trap with `$?` == 0 (#797), so the exit code
  # below cannot tell "finished green" from "was killed mid-gate". The signal
  # handler can, it already recorded the run, and it is the only witness of the
  # two that saw what happened.
  if [ -n "${navori_audit_signal:-}" ]; then
    return 0
  fi
  if [ "$navori_audit_code" -ne 0 ]; then
    navori_audit_log "block" "el quality gate no paso o no pudo correr" || true
  elif [ "$navori_audit_ran_gate" -eq 1 ]; then
    navori_audit_log "allow" "gate ejecutado y verde" || true
  else
    navori_audit_log "skip" "el comando no es un commit" || true
  fi
  return 0
}
trap navori_audit_on_exit EXIT
# Signal traps (TERM/INT/HUP) + `navori_audit_signal`. Shared body, single
# source of truth: the three gates are killed the same way and must record it
# the same way.
# Shared "the host cancelled this hook" recorder — inlined into the three gate
# hooks at render time (see the include directive in the source scripts +
# lib/render/hook-includes.ts).
#
# WHY (#797): a `command` hook that reaches its host timeout is CANCELLED, and
# bash still runs the EXIT trap on the way out with `$?` == 0 — the last
# COMPLETED command was the `trap` builtin itself. So the recorder's "exit code
# is zero" branch recorded a gate aborted after 3 seconds of a 20-second run as
# `allow`, "gate ejecutado y verde". Reproduced end to end on the RENDERED hook;
# the only trace of the truth was an `ms` nobody reads.
#
# That false green is worse than the absence it replaced: `quality-gate-aborted`
# only fires on a `gate-started` with NO terminal record, so the fake `allow`
# satisfied the detector and disarmed it. The signal itself is therefore the
# witness — recorded here, before the process dies, under its own verdict
# (`gate-killed`): never `allow`, never `block`. Nothing was validated, and the
# host had already discarded this hook's output when it sent the signal.
#
# The docs do not say WHICH signal the host uses to cancel, so this covers the
# handled ones (TERM/INT/HUP) while `gate-started` keeps covering SIGKILL, which
# no handler can ever observe. Both halves are needed: either one alone detects
# a scenario that may not be the one that happens.
#
# FAIL-OPEN like everything else in the recorder: the handler records, re-raises
# the ORIGINAL signal with its default disposition — so the process still dies
# from what it was sent instead of continuing as if nothing happened — and never
# changes what the host does with the tool call. It is deliberately NOT a
# process-tree kill: the gate's own child (`pnpm lint`, `semgrep`, `jscpd`)
# already outlives the hook today, and killing someone else's build from an
# observer is a decision of its own (#797, residue 3).
#
# SIGNAL DEFERRAL, so the recorded `ms` is not read as a second lie: bash does
# not run a trap while it waits for a foreground command, so under bash the
# record lands when the gate command FINISHES, not when the signal arrived. The
# verdict is the same either way and the host is long gone by then; only the
# instant differs.
#
# `navori_audit_signal` is what keeps the two recorders from both writing: the
# EXIT trap runs after this one and must stay quiet, since its `$?` is exactly
# the value that cannot be trusted here.
navori_audit_signal=""
navori_audit_on_signal() {
  navori_audit_signal=$1
  navori_audit_log "gate-killed" "cancelado por SIG$1: nada quedo validado" || true
  # `|| true` on both: a recorder may never become the reason a hook fails, and
  # `set -e` is on in every script that includes this.
  trap - "$1" 2>/dev/null || true
  kill -s "$1" "$$" 2>/dev/null || true
  return 0
}
trap 'navori_audit_on_signal TERM' TERM
trap 'navori_audit_on_signal INT' INT
trap 'navori_audit_on_signal HUP' HUP

# Detect the project's REAL package manager from lockfiles / package.json, so a
# gate command hardcoded to one PM (e.g. `pnpm run ...`) can still run in a repo
# that actually uses another (e.g. bun). Mirrors lib/detect.ts precedence:
# `packageManager` field first, then pnpm/bun/yarn/npm lockfiles. Prints the PM
# name (or nothing) on stdout. Git runs hooks from the repo root, so relative
# paths resolve against the project root.
detect_pm() {
  if [ -f package.json ]; then
    pm=$(sed -n 's/.*"packageManager"[[:space:]]*:[[:space:]]*"\([a-z]*\)@.*/\1/p' package.json | head -n1)
    case "$pm" in pnpm|npm|yarn|bun) printf '%s' "$pm"; return 0 ;; esac
  fi
  if [ -f pnpm-lock.yaml ]; then printf 'pnpm'; return 0; fi
  if [ -f bun.lockb ] || [ -f bun.lock ]; then printf 'bun'; return 0; fi
  if [ -f yarn.lock ]; then printf 'yarn'; return 0; fi
  if [ -f package-lock.json ]; then printf 'npm'; return 0; fi
  return 0
}

# True when the argument is a JS package manager (so we only try to remap the
# leading token of the gate command when it's actually a PM, not `make`/`ruff`).
is_pm() {
  case "$1" in pnpm|npm|yarn|bun) return 0 ;; *) return 1 ;; esac
}

run_gate() {
  navori_audit_ran_gate=1
  # The host can kill this process at its hook timeout, before our EXIT trap
  # records allow/block. Persist a start marker first; audit correlates it with
  # the terminal record by tool_use_id and reports an unfinished gate.
  navori_audit_log "gate-started" "inicio del quality gate" || true
  echo "[navori] running quality-gate fast: $1" >&2
  eval "$1" || {
    echo "[navori] quality-gate fast failed. Commit aborted." >&2
    exit 2
  }
}

# Gate to `git commit` only. $TRIGGER_RE is consumed by the shared detector
# inlined below.
TRIGGER_RE='^git([[:space:]]+-[a-zA-Z-]+(=[^[:space:]]+)?([[:space:]]+[^-][^[:space:]]*)?)*[[:space:]]+commit([[:space:]]|$)'
# Literal substrings every branch of $TRIGGER_RE needs; read by the fast
# path in the shared detector below (spec 0016). Keep NEXT to the regex:
# a branch added there without its token here silently loses the shortcut
# (fail-open to the slow path), and the inlined tests pin the pairing.
TRIGGER_TOKENS='commit'
# Shared gate detector — inlined into each hook at render time (see the include
# directive in the source scripts + lib/render/hook-includes.ts). The caller MUST set
# $TRIGGER_RE (an ERE) before the include; it decides which git ops this hook
# gates. Single source of truth for the FIX B/C wrapper-peeling logic; DO NOT
# copy this body into a hook by hand.
#
# Detect whether $1 (a possibly-compound command) invokes a gated operation.
# Splits $1 on the shell separators && || ; | and newlines, strips leading
# whitespace plus wrapper words (`(`, `\`, `command `) and `VAR=value` env
# prefixes from each segment, and returns 0 if ANY segment STARTS with a gated
# `git …` invocation on a word boundary (matched by $TRIGGER_RE). Replaces
# literal-prefix `case` matching, which silently skipped the gate for
# `cd x && git commit`, `echo y; git push`, or a leading space (#88: NEVER skip
# the gate silently). Matching a segment START means a quoted `echo "git commit"`
# does NOT trigger it. Known limitation: it cannot see through `sh -c`, `eval`,
# or obfuscation — a seatbelt, not a sandbox.
# The fast path on its own, so a caller can apply it EARLIER than the segment
# scan — before it has even paid to extract the command from the payload.
#
# Returns 0 when $1 may contain a gated operation, 1 when it provably cannot.
# The argument is the one the block below spells out: no $TRIGGER_RE can match
# without one of the caller's literal TOKENS appearing in the segment it
# matches, and every segment is a substring of the input. So the absence of
# every token is proof that no segment can match — and the same proof holds one
# level up, over the raw PAYLOAD the command was extracted from: JSON escaping
# touches `"`, `\` and control characters, never the letters of a token.
#
# Disarms when $TRIGGER_TOKENS is unset: with no tokens declared there is
# nothing to prove absent, so it answers "maybe" and the caller does the work.
# Fail-open to the SLOW path, never to a skip.
has_trigger_token() {
  [ -n "${TRIGGER_TOKENS:-}" ] || return 0
  # Token iteration goes through newline-split + `read`, NOT `for _tok in
  # $TRIGGER_TOKENS`: zsh does not word-split an unquoted expansion, so the
  # `for` form iterated ONCE with the whole list as a single token there — and
  # a token that can never match is a gate that never fires. Caught by the
  # bash×zsh differential suite.
  local _input="$1" _tok _nl=$'\n'
  local _toks="${TRIGGER_TOKENS// /$_nl}"
  while IFS= read -r _tok; do
    [ -n "$_tok" ] || continue
    case "$_input" in *"$_tok"*) return 0 ;; esac
  done <<< "$_toks"
  return 1
}

is_scan_trigger() {
  # Pre-expanded newline: zsh does NOT expand $'\n' in the REPLACEMENT of
  # ${var//pat/repl} (it inserts the literal characters), so an inline $'\n'
  # left compound commands unsplit there and the gate silently skipped
  # `cd x && git commit` (#391). A plain variable expands identically in
  # bash and zsh. ($'\n' in PATTERN position expands fine in both.)
  local input="$1" segment nl=$'\n'

  # ─── Fast path (spec 0016 T3.2, second pass): the loop below pays one
  # `grep -qE` FORK per segment — and a heredoc body or a 40-step compound
  # is 40 segments, so the field cost scaled with command length (measured:
  # 2.8 ms trivial, 14.8 ms for a 199-char heredoc, 95.8 ms for 40 segments;
  # p50 across one real session's commands was 40 ms per hook, not the
  # trivial floor). No $TRIGGER_RE can match without one of the caller's
  # literal TOKENS appearing in the segment it matches — and every segment is
  # a substring of the input, transformed only by insertions (`\<NL>` → space,
  # separators → newline) and prefix-peeling, none of which can CREATE a
  # token. So a single in-process substring scan of the raw input is a strict
  # superset of the segment matches: if no token is present, no segment can
  # match, and the gate answers "not for me" without a single fork. Same
  # argument, same safe direction, as the guard's own fast path.
  #
  # $TRIGGER_TOKENS is set by the including hook NEXT TO its $TRIGGER_RE, so
  # the pair travels together; when unset the fast path disarms and the loop
  # runs exactly as before (fail-open to the SLOW path, never to a skip).
  # Token iteration goes through newline-split + `read`, NOT `for _tok in
  # $TRIGGER_TOKENS`: zsh does not word-split an unquoted expansion, so the
  # `for` form iterated ONCE with the whole list as a single token there — and
  # a token that can never match is a gate that never fires. Caught by the
  # bash×zsh differential suite; same class as the $'\n' pitfall above.
  has_trigger_token "$input" || return 1
  # FIX B: join `\<newline>` continuations into a space FIRST, so a command
  # split across lines with a trailing backslash stays ONE logical segment
  # (otherwise the subcommand/flag lands in a segment not starting with git).
  input="${input//\\$'\n'/ }"
  input="${input//&&/$nl}"
  input="${input//||/$nl}"
  input="${input//;/$nl}"
  input="${input//|/$nl}"
  # `<<<` feeds the already-expanded value as data — no re-evaluation — so a
  # command that contains backticks/$() is inspected, never executed.
  while IFS= read -r segment; do
    segment="${segment#"${segment%%[![:space:]]*}"}"        # strip leading ws
    # FIX C: peel wrappers so `(git …`, `\git`, `command git …` and
    # `VAR=val git …` all reduce to a plain `git …` before matching.
    while [[ "$segment" == \(* ]]; do                       # strip leading ( runs
      segment="${segment#\(}"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    done
    segment="${segment#\\}"                                 # strip a leading backslash (\git)
    while [[ "$segment" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; do  # strip VAR=val prefixes
      case "$segment" in
        *[[:space:]]*)
          segment="${segment#*[[:space:]]}"
          segment="${segment#"${segment%%[![:space:]]*}"}"
          ;;
        *) segment=""; break ;;
      esac
    done
    if [[ "$segment" == command\ * ]]; then                 # strip a leading `command ` word
      segment="${segment#command }"
      segment="${segment#"${segment%%[![:space:]]*}"}"
    fi
    # FIX C: allow git global options between `git` and the subcommand
    # (`git -c k=v commit`, `git -C /repo push`). $TRIGGER_RE's trailing boundary
    # keeps `git commitgraph` / `git config …` from matching.
    if printf '%s' "$segment" | grep -qE "$TRIGGER_RE"; then
      return 0
    fi
  done <<< "$input"
  return 1
}

# Resolution of the working tree the commit acts on (#454). Shared body; defines
# `navori_worktree` but resolves nothing until it is called, so a Bash call that
# is not a commit still pays nothing for it.
# Shared worktree resolver — inlined into each gate hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Requires the
# `extract-cmd` partial to have run first ($payload and $cmd in scope).
#
# WHY (#454): settings.json invokes these hooks as
# `bash "$CLAUDE_PROJECT_DIR/.claude/scripts/check-semgrep.sh"`, so the hook
# PROCESS starts in the MAIN repo even when the commit happens inside an agent
# worktree under `.claude/worktrees/`. The old `cd "$(git rev-parse
# --show-toplevel)"` therefore resolved the main repo — whose tree is clean — so
# `git diff --name-only main` returned 0 files and the gate exited 0. Not a false
# negative from the scanner: the scanner never ran. A `cd` to an arbitrary tree
# is exactly the bug, so nothing below ever guesses: every candidate must prove
# it is a git working tree, or the next one is tried — and the one the COMMAND
# names must additionally prove it is part of the repository being protected
# (see the same-repository constraint in `navori_worktree`).
#
# `navori_worktree` prints the absolute root of the working tree the gated git
# command will act on, or nothing when none resolves. It is a FUNCTION, not a
# top-level assignment, because `quality-gate-pre-commit` inlines this partial on
# a path that runs on EVERY Bash tool call: callers pay the git/jq probes only
# after their own trigger matched.

# First shell token of $1: a leading single/double-quoted string (so a path with
# spaces survives) or an unquoted run of non-space characters.
navori_first_token() {
  local s="$1"
  case "$s" in
    \"*) s="${s#\"}"; printf '%s' "${s%%\"*}" ;;
    \'*) s="${s#\'}"; printf '%s' "${s%%\'*}" ;;
    *) printf '%s' "${s%%[[:space:]]*}" ;;
  esac
}

# Directory named by the command itself, if any. Two shapes, both real in this
# harness: `git -C <dir> commit …` (git names its own tree) and
# `cd <dir> && git commit …` (how an agent commits into its worktree from a
# session anchored elsewhere). Prints the raw token; the caller resolves it.
#
# TODO(scope): only the FIRST segment is inspected for `cd`. A `cd` buried
# mid-chain (`pnpm build && cd sub && git commit`) falls through to the payload
# cwd, which is right whenever that `cd` stays inside the same repo. Walk the
# segments if a real command shows up where it does not.
navori_cmd_dir() {
  local text="$1" rest="" head=""
  case "$text" in
    *"git -C "*)
      rest="${text#*git -C }"
      ;;
    *)
      head="${text%%&&*}"
      head="${head#"${head%%[![:space:]]*}"}"
      case "$head" in
        "cd "*) rest="${head#cd }" ;;
      esac
      ;;
  esac
  [ -n "$rest" ] || return 1
  rest="${rest#"${rest%%[![:space:]]*}"}"
  # A token that needs the shell to expand it ($VAR, `sub`, ~, globs) is NOT
  # resolved here: guessing wrong points the scan at the wrong tree, which is
  # the very failure this partial exists to kill. Ignoring it just falls through
  # to the next candidate.
  case "$rest" in
    ""|*'$'*|*'`'*|*'*'*|*'?'*|"~"*) return 1 ;;
  esac
  navori_first_token "$rest"
}

# Absolute, symlink-resolved path of a working tree's SHARED git dir, or nothing
# when $1 is not inside a git working tree. `--git-common-dir` names the `.git`
# of the MAIN checkout, so every linked worktree of one repository — and every
# subdirectory of it — reports the SAME value, while a different repository
# reports its own and a submodule reports `<main>/.git/modules/<name>`. That
# makes it an identity test for "same repository", which `--show-toplevel` (one
# per working tree) and `--git-dir` (one per worktree) are not.
navori_repo_id() {
  local dir="$1" common=""
  common=$(git -C "$dir" rev-parse --git-common-dir 2>/dev/null) || return 1
  [ -n "$common" ] || return 1
  # `git -C <dir>` chdirs to <dir> first, so a relative answer (`.git`,
  # `../../.git`) is relative to <dir>. `pwd -P` canonicalises both sides the
  # same way, which also settles macOS's /var vs /private/var symlink.
  (cd "$dir" && cd "$common" && pwd -P) 2>/dev/null
}

# First argument that resolves to a git working tree; prints its root.
navori_first_tree() {
  local candidate toplevel
  for candidate in "$@"; do
    [ -n "$candidate" ] || continue
    [ -d "$candidate" ] || continue
    toplevel=$(git -C "$candidate" rev-parse --show-toplevel 2>/dev/null) || continue
    [ -n "$toplevel" ] || continue
    printf '%s' "$toplevel"
    return 0
  done
  return 1
}

# Resolution, most specific first:
#   1. the directory the command names (`git -C` / a leading `cd`), ONLY when it
#      belongs to the same repository as the anchor (see the constraint below);
#   2. the payload's `.cwd` — Claude Code sends the CURRENT working directory of
#      the tool call, a documented field distinct from $CLAUDE_PROJECT_DIR (the
#      project root). In an agent worktree these differ; that gap IS #454;
#   3. the hook process's own cwd — the pre-#454 behaviour, still correct for a
#      plain terminal or git-hook invocation.
navori_worktree() {
  local payload_cwd anchor named anchor_repo="" named_repo=""
  payload_cwd=$(payload_field cwd)
  # A relative `cd sub` resolves against the shell's cwd, which is the payload's
  # when Claude Code sends one and the hook process's otherwise.
  anchor="$payload_cwd"
  [ -d "$anchor" ] || anchor="$PWD"
  named=$(navori_cmd_dir "$cmd" || true)
  case "$named" in
    "") ;;
    /*) ;;
    *) named="$anchor/$named" ;;
  esac
  # SAME-REPOSITORY CONSTRAINT — DO NOT REMOVE (#454, review finding).
  # Candidate 1 is the only one the COMMAND controls, and it is tried first, so
  # accepting any git tree it happens to name lets that command OVERRIDE the
  # trustworthy candidates below it: `git -C <other-repo> log && git commit`,
  # `cd <other> && cd <wt> && git commit`, `cd <sub> && cd .. && git commit`, or
  # merely the bytes `git -C <path>` inside a commit MESSAGE, all aimed the scan
  # at a foreign tree with nothing to scan — exit 0 with the scanner never run,
  # which is the very failure #454 is about (and, for a commit in the main repo,
  # strictly worse than not resolving worktrees at all).
  # So a directory the command names is accepted only when it is part of the
  # repository the hook is protecting, i.e. the anchor's. Linked worktrees share
  # the main checkout's git dir, so every legitimate agent worktree passes; a
  # different repository and a submodule (its own git dir under
  # `<main>/.git/modules/`) do not, and fall through to the payload cwd — the
  # stricter direction. An unresolvable anchor drops candidate 1 for the same
  # reason: nothing to check it against.
  # Ceiling: two linked worktrees of the SAME repository are indistinguishable
  # this way, so naming a sibling worktree still beats the payload cwd. Both are
  # trees of the repo being protected, so the scan stays inside it. Walk the
  # segments to the one that actually carries the `git commit` if a real command
  # shows up where that is not enough.
  if [ -n "$named" ]; then
    anchor_repo=$(navori_repo_id "$anchor" || true)
    named_repo=$(navori_repo_id "$named" || true)
    if [ -z "$anchor_repo" ] || [ "$named_repo" != "$anchor_repo" ]; then
      named=""
    fi
  fi
  navori_first_tree "$named" "$payload_cwd" "$PWD" || true
}

# An EMPTY `$cmd` is not "some command that isn't a commit": it means nothing
# could be read out of the tool input at all (no JSON parser, a malformed or
# truncated payload). `is_scan_trigger ""` simply finds no git segment, so the
# whole block below was skipped WITHOUT A WORD — a gate that omits itself in
# silence is indistinguishable from a gate that passed (#511). Its two siblings
# (`check-semgrep.sh`, `check-jscpd.sh`) already scan unconditionally there,
# which is the contract the shared extractor documents; this one drifted. The
# verdict is now stated out loud in both directions, per #88.
run_needed=0
if [ -z "$cmd" ]; then
  echo "[navori] no command could be read from the tool input; running the quality gate anyway rather than skipping it silently." >&2
  run_needed=1
elif is_scan_trigger "$cmd"; then
  run_needed=1
fi

if [ "$run_needed" = 1 ]; then
  # Pin the cwd to the root of the tree BEING COMMITTED before anything below
  # runs. Claude Code fires PreToolUse hooks from a cwd that is neither always
  # the repo root (#309: a relative gate like `cd packages/cli && pnpm lint`
  # fails from a subdir) nor always the right repo (#454: it is the MAIN repo
  # even when the commit happens in an agent worktree, so the gate validated a
  # tree that did not hold the diff).
  # $CLAUDE_PROJECT_DIR stays as a fallback for the no-git case; when nothing
  # resolves the substitution is empty and `cd ""` is a no-op, so behavior
  # outside a repo is unchanged.
  gate_root=$(navori_worktree)
  cd "${gate_root:-${CLAUDE_PROJECT_DIR:-}}" || exit 2
  # qualityGate.fast is shell-quoted at render time via the shq: marker (#197).
  # The gate string is still `eval`'d by run_gate below (running the gate is the
  # feature), but quoting it here means a hostile qualityGate.fast survives as one
  # literal token instead of injecting commands at variable-assignment time.
  gate='ruff check .'
  gate_bin="${gate%% *}"
  if command -v "$gate_bin" >/dev/null 2>&1; then
    run_gate "$gate"
  else
    # The declared runner isn't on PATH. If it's a package manager, detect the
    # repo's real one from lockfiles and retry through it (a `pnpm run x` gate
    # still runs in a bun-only checkout). #88: NEVER skip the gate silently —
    # when nothing can run it, BLOCK the commit loudly instead of the old
    # `exit 0` that handed a contributor zero quality gate without a word.
    detected_pm="$(detect_pm)"
    if is_pm "$gate_bin" && [ -n "$detected_pm" ] && [ "$detected_pm" != "$gate_bin" ] && command -v "$detected_pm" >/dev/null 2>&1; then
      echo "[navori] '$gate_bin' is not on PATH; using the lockfile-detected package manager: '$detected_pm'." >&2
      run_gate "$detected_pm ${gate#* }"
    else
      echo "[navori] quality-gate NOT run: '$gate_bin' is not on PATH and no alternative package manager was detected that could run it." >&2
      echo "[navori] Commit BLOCKED to avoid skipping the gate silently. Install '$gate_bin', or if you really want to skip it run the commit yourself outside the agent." >&2
      exit 2
    fi
  fi
fi
# navori:managed end id="qg-pre-commit-base"

# user: add extra checks here. `$cmd` is already parsed from the tool input.
# Example:
#
#   case "$cmd" in
#     'git push'*)
#       bash scripts/check-licenses.sh || exit 2
#       ;;
#   esac
#
# Use a path your own repo owns. The example used to point at a plugin script
# under `.claude/scripts/`, which only exists when that plugin is installed AND
# the engine is Claude — copied verbatim it fails under Codex (#389).
