# navori:managed start id="routing-watch-base" hash="5495c1a9" version="0.10.0" source="@navori/core"
#!/usr/bin/env bash
#
# PostToolUse routing watcher (spec 0020).
#
# WHY THIS EXISTS. The routing ladder ships as CLAUDE.md context, and the host's
# own documentation says what that buys: "Claude treats them as context, NOT
# enforced configuration... If the instruction is something that must run at a
# specific point, write it as a hook instead." Measured over 48 audited
# sessions, 21 crossed the delegation threshold of the day and 12 of those (57%) delegated nothing
# — including a session in this very repo that wrote 26 files with zero
# subagents while carrying the ladder in its context. Prose was not the missing
# piece; a mechanism at the moment of the decision is.
#
# WHAT IT DOES, and what it deliberately does NOT. It counts the distinct files
# written in a session, and the first time that count reaches the threshold with
# no subagent yet invoked it hands the model ONE advisory note through
# `hookSpecificOutput.additionalContext`. It never blocks: a `PreToolUse` deny
# could stop the fifth edit until something is delegated, and was rejected on
# two measured grounds — sometimes inline IS correct (an operator can forbid
# delegation outright, and a block would leave that session with no way out),
# and a mechanism that gets ignored erodes the authority of the ones that are
# obeyed. The note turns an invisible decision into an explicit one; that is the
# gap, not a prohibition.
#
# WHY `PostToolUse` AND NOT `UserPromptSubmit`. The threshold is crossed by an
# EDIT, not by a prompt. This fires immediately after the edit that crosses it,
# which is the moment of the decision; `UserPromptSubmit` fires before the model
# has done anything that turn, i.e. at the wrong time.
#
# WHY THE THRESHOLD IS STILL "4 DISTINCT FILES". It was the objective half of a
# routing rule that has since been withdrawn — the ladder it belonged to had its
# threshold written in seven places that did not agree, so it was collapsed to a
# single route: every change to source goes through implementer -> reviewer.
#
# Under one route the honest threshold is ONE file, not four. What it counts is
# now right — repo-relative, and only paths that carry behavior, from the same
# definition the miner and the pilot use — but the NUMBER stays at four until the
# ruling returns, because lowering it is a decision about how loud this should
# be, not about what it measures. Meanwhile 4-and-no-delegation catches the worst
# deviations and stays quiet on the rest.
#
# WHY IT DOES NOT TRY TO TELL THE MAIN THREAD FROM A SUBAGENT — this is what
# keeps the script small. The condition is "N files AND zero delegation": if a
# subagent wrote something, then delegation happened, and the condition is
# already false by its second half. Over-counting is harmless by construction.
# It matters because the `PostToolUse` payload carries NO agent identifier (the
# `agentId` the audit log writes is really the `cwd`), so the alternative would
# have been an invented heuristic.
#
# FAIL-OPEN, ALWAYS. Every path exits 0, including "cannot read or write the
# stamp" (read-only FS, odd $HOME). A `PostToolUse` hook runs after tool calls
# all session long; failing loudly there is worse than not warning at all. Note
# the deliberate absence of `-e` in the `set` line below.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -uo pipefail

# Payload extraction (stdin → `payload` + `payload_field`). Shared body, single
# source of truth: the jq → node → sed cascade exists because jq is NOT
# preinstalled on macOS, and four hand-synced copies of it is how #225/#261
# drifted. The partial defines `extract_cmd` but does NOT call it: this hook
# never reads `tool_input.command`, and a spawn it cannot use would be charged to
# every tool call in every session.
#
# ORDER BELOW IS A COST DECISION, and these are the counts it buys. Every
# `payload_field` call may spawn a process, so nothing is read before the field
# that can end the run:
#   1 spawn  — any tool that is not Edit/Write/NotebookEdit/Agent/Bash:
#              `tool_name` alone, and the discard `case` exits.
#   1 spawn  — a `Bash` carrying no write token at all: the fork-free probe
#              right after that `case` ends the run before anything locates a
#              stamp. Measured over the park, 53.8% of Bash calls — and Bash is
#              80.4% of every tool call — so this is the dominant path.
#   2 spawns — a session already `#delegated` or `#notified`: + `session_id`,
#              which is what names the stamp, and the stamp check exits.
#   4 spawns — an edit that actually counts: + `agent_id` (the subagent guard
#              below) + the file path.
#   5 spawns — a `Bash` whose PAYLOAD looked like a write but whose COMMAND is
#              not one: + `extract_cmd`, and the same probe re-applied to the
#              command ends it one fork before the extraction pipeline.
# The discard `case` therefore comes BEFORE `session_id`: a tool this hook does
# not care about must not pay to locate a stamp it will never open. The Bash
# probe is that same argument one level down — see `navori_has_write_token`.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.

# R5 (spec 0020): the notice has to be COUNTABLE, not just visible. A hook is
# invisible to the transcript unless it blocks or injects, and this one injects
# exactly once per session — so without a record in the audit log there is no
# way to ask "how often did the ladder actually fire, and did delegation follow?"
# That question is the whole success criterion of the spec, and #623 is the
# standing proof that "the hook emitted it" and "the model got it" are different
# claims: the log is what lets the transcript be read back against the emission.
#
# ONLY the notify path records. This hook fires on every write tool of every
# session; recording each firing would bloat the log with the one verdict nobody
# asked about. One line per session, on the event that matters.
navori_audit_name="routing-watch"
navori_audit_phase="PostToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# Same reason as in `managed-drift-watch`: a raw, unexpanded copy of this asset
# must degrade to silence, never to exit 127.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/render/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  # The third field is the OWNER, and it is never empty: inside a subagent the
  # host sends a real `agent_id`; on the main thread it sends none and the
  # literal below names the orchestrator explicitly.
  #
  # It used to be `// ""`, and the empty case did not stay empty — it came out
  # as the `cwd`. Command substitution strips trailing newlines, so an empty
  # third field left `$navori_audit_fields` with only two lines; then
  # `${rest#*<NL>}` found no newline in `"cwd"` and POSIX says a `#` pattern
  # that does not match returns the string UNCHANGED. 41,581 of the park's
  # 52,460 recorded owners (79%) were a filesystem path for that reason.
  #
  # The consumer's behaviour does not change — `ownerOf` looks the value up
  # among the session's agents and sends anything that names nobody to the
  # orchestrator, which is where a path already went — but the record stops
  # claiming the repo directory is an agent. Old logs keep working through the
  # same "names nobody" branch.
  #
  # The trailing "." is a sentinel, not data: with it the third field is always
  # followed by a newline, so the `%%` below cannot fall into the same trap if
  # a future field is ever empty.
  #
  # The owner is picked with an explicit "first non-empty string", NOT with
  # `.agent_id // .subagent_id // "orchestrator"`. In jq only `null` and `false`
  # are falsy, so a host that sends the key with an EMPTY string satisfies `//`
  # and the chain yields `""` — the field then disappears from the record and
  # `ownerOf` falls back to the time window, which is the guess this field
  # exists to avoid. Caught by a test, not by review.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", ([.agent_id, .subagent_id] | map(select(type == "string" and . != "")) | first) // "orchestrator", .tool_use_id // "", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_tool_use_id=${navori_audit_rest%%
*}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  if [ ! -f "$navori_audit_file" ]; then
    # SPOOL for the phase that CANNOT have a log yet (#778).
    #
    # `navori audit --start` is what creates the session log, and it runs from
    # the UserPromptSubmit hook — i.e. after the first prompt. Every SessionStart
    # hook therefore fires BEFORE the file exists, and the check above threw its
    # record away every single time: measured, `session-start-context` recorded 1
    # of ~20 startups in this repo, and the only survivor was a resume onto an
    # already-open log. "Did the session load the harness?" had no witness at all,
    # which is exactly the question the recorder exists to answer.
    #
    # So those records go to a side file that `--start` absorbs. Two deliberate
    # limits keep this from becoming a leak:
    #
    #   1. SessionStart ONLY. Every other phase runs after a prompt, so a missing
    #      log there means the session is genuinely not marked — and spooling
    #      those would write four lines per Bash call, for every session of every
    #      repo, forever. That is thousands of writes to buy nothing.
    #   2. Only where the repo's audit directory ALREADY exists, which means the
    #      repo has been audited (or armed) at least once. `mkdir` is never run
    #      from here: a repo that has never used audit-mode must stay at zero
    #      files and zero forks, the same contract as the root gate above. The
    #      cost is that the FIRST audited session of a repo still loses its
    #      SessionStart records; every one after it has them.
    #
    # FAIL-OPEN, and here more than anywhere: this runs while a session is
    # opening. Every failure path below returns 0 and writes nothing to stdout —
    # a spool that could abort a hook would make observation the reason a session
    # does not start, which is the one bug this partial may never have.
    [ "${navori_audit_phase:-}" = "SessionStart" ] || return 0
    [ -d "$navori_audit_root/$navori_audit_repo" ] || return 0
    navori_audit_file=$navori_audit_root/$navori_audit_repo/pending-$navori_audit_session.jsonl
    if [ ! -e "$navori_audit_file" ]; then
      : >> "$navori_audit_file" 2>/dev/null || return 0
    fi
  fi
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  # `tsMs` is the instant at the resolution the log actually needs (#685): the
  # `ts` below truncates to the second, and 84% of a measured session's events
  # share their second with another one. This value is already computed — the
  # duration above is derived from it — so recording it costs nothing.
  #
  # Validated with the same `-ge 0` idiom as `ms`, and for the same reason: it
  # is passed as `--argjson`, so a non-numeric value would make the whole `jq`
  # fail and the event would vanish instead of merely losing a field.
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0

  # `ts` is NOT stamped here, and that is the whole point of #696: it was a
  # `date` fork per event — 46,850 of them across this store — for a string
  # fully derivable from the `tsMs` above, which `$EPOCHREALTIME` already
  # produced without spawning anything. The file's own cost doctrine (see
  # `navori_audit_now`) says spend a process only when there is no other way;
  # keeping this one made the comment lie four lines under the value that
  # refutes it.
  #
  # Nothing downstream lost a field: `parse.ts` derives the ISO from `tsMs`
  # when the record carries none, and logs written before this still have
  # theirs. The lifecycle records — `start`, `stop`, `session-end` — keep a real
  # `ts`, so a human reading the raw `.log` still has dated anchors; those are
  # ~3 per session, not one per hook.
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --arg toolUseId "${navori_audit_tool_use_id:-}" \
    --argjson ms "$navori_audit_ms" \
    --argjson tsMs "$navori_audit_end" \
    '{tsMs:$tsMs,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)
     + (if $toolUseId == "" then {} else {toolUseId:$toolUseId} end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

# See the header for why this is still 4 and not 1. Changing this number changes when
# the note fires and nothing else.
threshold=4

# The fork-free write probe, and why the Bash lane needs one at all.
#
# BOUNDED WORK, the discipline `guard-destructive` states outright: discard as
# early as possible, with the cheapest work that can decide. Measured over the
# park (41,889 tool calls, 33,686 of them Bash), the lane WITHOUT this probe
# sends 85.9% of Bash calls into the extraction and 2.6% of those contribute a
# single path — 97.4% of the work counts nothing. The cause is that the old gate
# tested three bare substrings against the WHOLE payload, and a `PostToolUse`
# payload carries `tool_response` too: `*sed*` matched every `sed -n` READ and
# every output containing the word "used", `*">"*` matched `2>/dev/null` and
# every `-->` in a diff someone happened to print.
#
# So this asks a narrower question — "could this text contain a redirect or an
# in-place edit that NAMES a file?" — with shell builtins only, no fork. It is a
# strict SUPERSET of what the extraction below can find, which is the one
# property that makes it safe as a gate: the same argument `has_trigger_token`
# makes for the gate hooks' fast path. A false positive costs a fork; a false
# negative is a count that silently stops happening, so the asymmetry decides
# every judgement call below.
navori_has_write_token() {
  # The patterns travel through variables rather than inline: `/` closes the
  # pattern in `${var//pat/repl}`, and an expansion carries the literal past
  # that parse identically in bash 3.2 and zsh (pinned by the differential
  # suite, which runs this hook under both).
  local probe=$1 devnull='>/dev/null' devnull_spaced='> /dev/null'
  # The noise that provably names no file. Only two forms qualify, and which
  # ones was settled AT THE SHELL against the extraction below, not by reading
  # the regex:
  #   `>&`  — after it the operand class rejects the next character, so
  #           `cmd >& src/a.ts` extracts NOTHING. Safe to strip.
  #   `/dev/null` — the sink a large share of the park's commands redirect to;
  #           it extracts, but as an absolute path the loop drops it anyway.
  #
  # `&>` is NOT here, and that is the whole point of this comment. It reads like
  # `>&` reversed, but it is a REAL redirect: `cmd &> src/a.ts` extracts
  # `src/a.ts` and the hook counts it. Stripping it deleted the `>` before the
  # probe could see it, so four `&>` writes to source left the stamp EMPTY and
  # the notice silent — this issue's own defect class, reintroduced by the
  # commit that fixes it. Nothing may be added to this list without a shell
  # check that the extraction really finds nothing after it.
  probe=${probe//>&/}
  probe=${probe//$devnull/}
  probe=${probe//$devnull_spaced/}
  case "$probe" in
    *">"*) return 0 ;;
  esac
  # `>>` is deliberately NOT stripped above, for the same reason. The
  # extraction's `grep -oE` matches the SECOND `>` of an append and counts its
  # operand, so dropping appends here would silently stop counting
  # `cat >> src/a.ts`.
  #
  # These two mirror the extraction's non-redirect branches, separators and all:
  # a bare `*tee*` matched "committee" and a bare `*sed*` matched "used".
  case "$1" in
    *"tee "*) return 0 ;;
    *"sed "*-i*) return 0 ;;
  esac
  return 1
}

tool=$(payload_field tool_name)
[ -n "$tool" ] || exit 0
navori_audit_tool=$tool

# The cheap discriminator, and the only thing read so far. Anything this hook has
# no business with leaves here, having spawned exactly once.
case "$tool" in
  Agent | Task | Edit | Write | NotebookEdit) ;;
  # #722 A4: a `Bash` that WRITES counts too. Without it the threshold only ever
  # accumulated through the native lane — the one the dominant mode abandons
  # (80.4% of the park's 41,889 measured tool calls are Bash) — so in the
  # sessions this notice exists for it was structurally unreachable.
  #
  # That branch then shipped INERT for weeks (#775): the matcher this hook is
  # registered with never gained `Bash`, and the host filters by matcher before
  # it spawns the script, so a `case` arm alone decides nothing. The number
  # above used to read 84.9% here and 80.4% in `build-settings.ts`; one
  # measurement, so now one number.
  Bash) ;;
  *) exit 0 ;;
esac

# Rung 1 of the Bash lane, and the earliest point at which it can end. No write
# token anywhere in the payload means no redirect, no `tee` and no `sed -i`, so
# there is nothing here this hook could ever count. It costs no fork and it runs
# BEFORE `session_id`: a shell command that writes nothing must not pay to
# locate a stamp it will never open, for the same reason a `Read` does not pay
# for the `case` above.
if [ "$tool" = "Bash" ]; then
  navori_has_write_token "${payload:-}" || exit 0
fi

# One stamp per session, so two concurrent sessions never overwrite each other's
# count. Sanitised because the value lands in a path: anything that is not a
# plain identifier character is dropped rather than escaped.
sid=$(payload_field session_id | tr -cd 'A-Za-z0-9._-')
[ -n "$sid" ] || sid="unknown-session"

stamp_dir=".claude/.routing-watch"
stamp="$stamp_dir/$sid"

# Append a line unless it is already there. Silent on every failure: a stamp
# that cannot be written means no note, never an error.
mark() {
  mkdir -p "$stamp_dir" 2>/dev/null || return 0
  # First write of THIS session's stamp: sweep siblings older than 7 days.
  # One `find` over a tiny dir, once per session — without it the directory
  # grows by one file per session forever (no SessionEnd hook owns it). Age,
  # not session-end, on purpose: `--resume` reuses the session id, and a
  # delete-on-end would re-arm the once-per-session notice on every resume.
  [ -e "$stamp" ] || find "$stamp_dir" -type f -mtime +7 -delete 2>/dev/null || true
  grep -q -F -x "$1" "$stamp" 2>/dev/null && return 0
  printf '%s\n' "$1" >> "$stamp" 2>/dev/null || true
}

case "$tool" in
  # Delegation happened. `Agent` is the name this host gives the subagent tool
  # (the same string `lib/audit/parse.ts` filters transcripts by); `Task` is
  # accepted too so a rename does not silently turn the detector off.
  Agent | Task)
    mark "#delegated"
    exit 0
    ;;
esac

# Delegated, or already warned: there is nothing left to decide this session.
# This is also the guarantee behind "at most once" — the stamp survives a
# compaction, so a note that scrolled out of context is NOT re-emitted.
# Repeating is what turns a signal into noise.
grep -q -E '^#(delegated|notified)$' "$stamp" 2>/dev/null && exit 0

# Hooks run INSIDE subagents too — the host fires the same PostToolUse for a
# subagent's tool calls, adding `agent_id` to the payload (empty in the main
# conversation). And the `#delegated` mark from the `Agent` case above only
# lands when that tool RETURNS, i.e. after the subagent already finished. So
# without this check a delegated implementer's own 4th edit would fire the
# notice INTO THE SUBAGENT'S context — "no subagent has been invoked" is false
# there, the advice is unactionable there (no Agent tool in its allowlist) —
# and would burn the once-per-session note before the orchestrator could ever
# receive it. An edit arriving from inside a subagent IS proof of delegation,
# so it is recorded as exactly that.
agent=$(payload_field agent_id)
if [ -n "$agent" ]; then
  mark "#delegated"
  exit 0
fi

# Clause (a) of "non-trivial source file", generated from the single TypeScript
# definition (`lib/source-classify.ts`). Inlined rather than called: this hook
# runs on EVERY PostToolUse, and `navori_is_source` is `[[ =~ ]]` — a builtin, so
# classifying a path costs no process.
# GENERATED by `bun run gen:schemas` from packages/cli/src/lib/diagnose/source-classify.ts.
# Do not edit: edit the module. A drift test fails if this falls behind.
#
# navori_is_source <repo-relative-path> — exit 0 when the path carries behavior
# (clause (a) of "non-trivial source file"), 1 otherwise.
#
# Clause (c) — a test riding along does not count twice — is NOT decided here:
# it needs the whole set of paths in one change, and a caller that has only one
# path at a time cannot apply it. Callers that count per file are computing a
# ceiling, exactly like the TypeScript side says.
navori_is_source() {
  [ -n "${1:-}" ] || return 1
  local _p
  # ephemeral: agent handoffs and reclaimed worktrees: never versioned, never in a diff
  _p='(^|/)\.claude/(progress|worktrees)/'; [[ $1 =~ $_p ]] && return 1
  # ephemeral: throwaway scaffolding; 13.4% of the miner's old 'source' writes were this
  _p='(^|/)(scratchpad|\.scratch)/'; [[ $1 =~ $_p ]] && return 1
  # dependency: a vendored dependency is not ours to change, and a write there is an accident
  _p='(^|/)node_modules/'; [[ $1 =~ $_p ]] && return 1
  # dependency: build output: regenerated from the source this same change may edit
  _p='(^|/)(dist|build|out|coverage|\.next|\.astro)/'; [[ $1 =~ $_p ]] && return 1
  # generated: the rendered harness mirror — the change lives in the source asset, not here
  _p='(^|/)\.claude/'; [[ $1 =~ $_p ]] && return 1
  # generated: rendered from managed blocks; editing it directly is what the drift guard blocks
  _p='(^|/)(CLAUDE|AGENTS)\.md$'; [[ $1 =~ $_p ]] && return 1
  # generated: rendered from the plugin manifests; editing it here is overwritten next render
  _p='(^|/)\.mcp\.json$'; [[ $1 =~ $_p ]] && return 1
  # generated: regenerated from the tree it pins; never hand-authored
  _p='(^|/)__golden__/|\.snap$'; [[ $1 =~ $_p ]] && return 1
  # lockfile: resolved by a tool, reviewed as a diff of intent elsewhere
  _p='(^|/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock|bun\.lockb?|Cargo\.lock|poetry\.lock|Gemfile\.lock|go\.sum)$'; [[ $1 =~ $_p ]] && return 1
  # fixture: data the tests read, not behavior the program runs
  _p='(^|/)(__fixtures__|__mocks__|fixtures)/'; [[ $1 =~ $_p ]] && return 1
  # test: clause (c): a test pinning a change counted elsewhere is evidence, not a second file
  _p='\.(test|spec)\.[mc]?[jt]sx?$'; [[ $1 =~ $_p ]] && return 1
  # test: same clause, for repos that group tests by directory instead of by suffix
  _p='(^|/)(__tests__|tests?)/'; [[ $1 =~ $_p ]] && return 1
  # test: same clause, Python and Go naming
  _p='(^|/)(test|tests)_[^/]+\.py$|(^|/)[^/]+_test\.(py|go)$'; [[ $1 =~ $_p ]] && return 1
  # config: clause (a) excludes config explicitly
  _p='(^|/)(package\.json|tsconfig[^/]*\.json|jsconfig\.json|biome\.jsonc?|\.eslintrc[^/]*|\.prettierrc[^/]*|\.editorconfig|\.gitignore|\.npmrc|\.nvmrc)$'; [[ $1 =~ $_p ]] && return 1
  # config: declares what the harness renders; the behavior it changes is navori's, not the repo's
  _p='(^|/)navori\.config\.json$'; [[ $1 =~ $_p ]] && return 1
  # docs: read by humans; no agent obeys it as instruction
  _p='(^|/)(docs|specs)/|(^|/)(README|CONTRIBUTING|CHANGELOG|LICENSE)[^/]*$'; [[ $1 =~ $_p ]] && return 1
  # docs: the session log, versioned but not behavior
  _p='(^|/)progress/'; [[ $1 =~ $_p ]] && return 1
  # Harness prose an agent obeys is behavior even though it is .md.
  _p='(^|/)(core-assets|plugins)/(.*/)?(agents|skills|managed)/[^/]+\.md$'; [[ $1 =~ $_p ]] && return 0
  _p='\.(ts|tsx|mts|cts|js|jsx|mjs|cjs|py|go|rs|java|kt|rb|php|cs|swift|sh|bash|zsh|sql|vue|svelte|astro|ipynb)$'; [[ $1 =~ $_p ]] && return 0
  return 1
}

# The candidate targets: one for a native tool, possibly several for a shell
# command that writes more than once.
if [ "$tool" = "Bash" ]; then
  # Rung 1 already ran, way up next to the tool `case`, so reaching here means
  # the payload carries a write token somewhere. Now it is worth one fork to
  # find out WHERE.
  navori_cmd=$(extract_cmd)
  [ -n "$navori_cmd" ] || exit 0
  # Rung 2: the same probe, on the COMMAND this time. Rung 1 had to read the
  # whole payload — which carries `tool_response`, i.e. the command's own
  # OUTPUT — so all it can answer is "maybe"; this answers "yes". Measured, it
  # ends a further 25% of the park's Bash calls one fork before the extraction
  # pipeline below (three more) would have found nothing (same discipline as
  # #716: the second payload read has to be earned, and so does the third).
  navori_has_write_token "$navori_cmd" || exit 0
  # The three forms `guard-destructive` rule 6 recognizes. One `grep -oE` pass,
  # because a shell-level parse of every redirect is not worth a fork per
  # operand — and this is a counter, not a gate.
  #
  # APPENDS ARE COUNTED, and this comment used to claim the opposite ("`>>` and
  # `tee -a` append, which is why neither appears here"). The pattern below has
  # no `>>` branch, but it does not need one: scanning left to right, the first
  # `>` of a `>>` fails (the next character is `>`, which the operand class
  # excludes) and the SECOND one matches, so `cat >> src/a.ts` yields
  # `src/a.ts`. Verified at the shell, not read off the regex. Counting it is
  # the right answer — appending to a source file is writing to it — so the
  # behaviour stays and the claim goes. `tee -a` genuinely does not count: its
  # operand is the flag, which the `grep -v '^-'` below drops.
  # `navori_has_write_token` depends on this being true, which is why it is
  # written down instead of inferred.
  files=$(printf '%s' "$navori_cmd" | grep -oE '(>\|?[[:space:]]*|(^|[[:space:]])tee[[:space:]]+)[^[:space:]|&;<>]+' 2>/dev/null \
    | sed -E -e 's/^[[:space:]]*//' -e 's/^>\|?[[:space:]]*//' -e 's/^tee[[:space:]]+//' -e 's/^[[:space:]]*//' \
    | grep -v '^-' || true)
  # `sed -i` names its target last, and the redirect pass above cannot see it.
  case "$navori_cmd" in
    *"sed "*-i*)
      navori_last=${navori_cmd##* }
      case "$navori_last" in
        -*) ;;
        *) files=$(printf '%s\n%s' "$files" "$navori_last") ;;
      esac
      ;;
  esac
else
  files=$(payload_field tool_input.file_path)
  # NotebookEdit has carried its target under `notebook_path` in some host
  # versions; without this the tool would contribute nothing and never say so.
  [ -n "$files" ] || files=$(payload_field tool_input.notebook_path)
fi
[ -n "$files" ] || exit 0

while IFS= read -r file; do
  [ -n "$file" ] || continue
  # Quotes survive the extraction above; a path is what is inside them.
  file=$(printf '%s' "$file" | tr -d "\"'")

  # Repo-relative, or not counted at all. The hook `cd`s to CLAUDE_PROJECT_DIR
  # above, so $PWD is the repo root.
  #
  # Without this the count included files that reach no diff: a scratch script
  # under /tmp, another repo's file opened in the same session. Measured on the
  # park, 13.4% of what the activation miner called "source writes" were exactly
  # that — and this hook had the same hole, so its notice could fire on a session
  # that had written nothing but scaffolding.
  case $file in
    "$PWD"/*) file=${file#"$PWD"/} ;;
    /*) continue ;;
  esac

  # And only what carries behavior. A render that rewrites 45 mirror files is not
  # a change anyone should delegate, and counting it as four was how this notice
  # could fire on a release.
  navori_is_source "$file" || continue

  mark "path:$file"
done <<NAVORI_FILES
$files
NAVORI_FILES

count=$(grep -c '^path:' "$stamp" 2>/dev/null) || count=0
[ "${count:-0}" -ge "$threshold" ] 2>/dev/null || exit 0

mark "#notified"
navori_audit_log "notify" "$count archivos del hilo principal, sin subagente"

# Written with no `"` and no `\` on purpose: that is what makes the JSON
# escaping below exact without a JSON encoder (see the awk join).
notice=$(cat <<MSG
navori: routing check. ${count} distinct files written in this session, and no subagent has been invoked.

Apply the enabled orchestration route for this repo. Do not route to an agent that this repo disabled.

If inline IS the right call here (the operator ruled delegation out, the edits are one mechanical change, the context is already paid for), say so explicitly in your next message and carry on. The point of this note is that the override stops being silent - today it leaves no trace at all.

Advisory only: nothing was blocked, and this fires at most once per session.
MSG
)

# JSON-escape by joining the lines with a literal backslash-n. Exact because the
# text above is a fixed literal free of quotes and backslashes; a payload from
# outside would need a real encoder.
escaped=$(printf '%s\n' "$notice" | awk 'NR>1 { printf "\\n" } { printf "%s", $0 }')
printf '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":"%s"}}\n' "$escaped"

# The last word of the script, and the contract of the whole file: advisory.
exit 0
# navori:managed end id="routing-watch-base"
