# navori:managed start id="subagent-no-background-base" hash="e5fa6ecd" version="0.10.0" source="@navori/core"
#!/usr/bin/env bash
#
# PreToolUse(Bash|Monitor) guard — the mechanical half of the "no backgrounding
# inside a subagent" rule (`implementer.md:43`, `reviewer.md:79`,
# `verify-before-done.md`'s subagent row): a subagent must run its chained
# steps one by one in the foreground, or report `Status: BLOCKED` — never
# background a gate it will not be re-woken to read. Blocks with `exit 2`, the
# same channel `guard-destructive`/`implementer-no-markdown` use, evaluated
# BEFORE permission rules.
#
# WHY A HOOK AND NOT JUST THE CONTRACT. The prose already states the rule in
# three places and it is not holding — a subagent has been observed stopping
# "with background work of its own still running", the exact failure the rule
# exists to prevent (#1003). This is the mechanical backstop.
#
# WHO IT APPLIES TO. `agent_id` — read straight from the payload, present only
# when the hook fires inside a subagent call
# (https://code.claude.com/docs/en/hooks) — gates this, NOT `agent_type`: the
# rule is role-agnostic (implementer, reviewer, auditor, scribe, scout...),
# unlike `implementer-no-markdown.sh` which is scoped to one role. Absent →
# the main thread, never blocked: backgrounding there IS the documented,
# legitimate path for a gate that outlives the Bash timeout
# (`verify-before-done.md`'s main-session row) — a hook that blocked it too
# would contradict the very rule it enforces.
#
# `Monitor` — blocked UNCONDITIONALLY inside a subagent, no field to inspect:
# the call itself is the violation. Its hookability as a `PreToolUse` tool
# name is NOT confirmed by the official hooks doc (no fixed tool list is
# published there); this branch is defense in depth, inert rather than wrong
# if the tool name never reaches a hook in practice.
#
# OUT OF SCOPE ON PURPOSE. Bare shell `&` inside a Bash `command` is NOT
# detected here — same posture `guard-destructive.sh` and
# `implementer-no-markdown.sh` already take for text-based command matching:
# `&&`, `2>&1`, `&>` and `&` inside a quoted string are real false positives a
# regex over unsegmented command text cannot fully separate, and the payoff
# does not justify the segmentation machinery `guard-destructive.sh` needed to
# solve the analogous problem. That vector stays enforced by prose only.
#
# KNOWN, ACCEPTED LIMITATION — the fail-open gotcha. `payload_field`'s sed
# fallback (`_partials/extract-cmd.sh`) only matches a QUOTED JSON STRING
# value; `tool_input.run_in_background` is a JSON BOOLEAN (unquoted `true`),
# so when neither `jq` nor `node` is on the host, the sed fallback returns
# empty and this hook reads that as "not backgrounded" — it FAILS OPEN. Same
# fail-open philosophy this repo already documents explicitly
# (`implementer-no-markdown.sh`, `guard-destructive.sh`'s own header): an
# accepted, precedented tradeoff, not an oversight.
#
# CODEX. This asset still renders to `.codex/hooks/` (generic asset copy,
# `placeHook`), but it is NOT wired into Codex's `config.toml`
# `[[hooks.PreToolUse]]`, same as `implementer-no-markdown.sh`
# (`specs/0030-scribe-owns-markdown/design.md`): Codex's hook payload has no
# confirmed `agent_id`/`agent_type` equivalent to gate on, so wiring it there
# would either fire for every agent including the main thread, or never
# resolve who is calling. The rule reaches Codex as prose only.
#
# The managed block below is regenerated by `navori render` and must NOT be
# edited by hand.
set -euo pipefail

# Command/field extraction (payload → $cmd, $payload). Shared body, single
# source of truth.
# Shared hook boilerplate — inlined into each hook at render time (see the
# include directive in the source scripts + lib/render/hook-includes.ts). Single source
# of truth for the sibling gate scripts; DO NOT copy this body back into a hook
# by hand (that is the drift #225/#261 removed).
#
# PreToolUse(Bash) passes the tool input on stdin. Read one field out of it
# WITHOUT hard-depending on jq (NOT preinstalled on macOS): try jq, then node
# (Claude Code's own runtime), then a best-effort sed unwrap on the leaf key.
# Nothing extracted → empty output, and each caller decides what that means (the
# gate scripts scan defensively; guard-destructive waves the command through).
#
# $1 is a dotted path written HERE, never user input — the payload is the data.
# Generic on purpose: `.cwd` feeds the worktree resolver of #454 through the
# SAME hardened cascade instead of a second copy of it.
#
# The sed fallback reads a JSON string through its first unescaped quote. JSON
# object member order is not a host contract: `command` can precede `cwd`, so a
# greedy capture to the last quote would swallow the rest of the payload when
# neither jq nor node is available.
payload=$(cat)
payload_field() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$payload" | jq -r ".$1 // empty" 2>/dev/null && return 0
  fi
  if command -v node >/dev/null 2>&1; then
    printf '%s' "$payload" | node -e 'let s="";const p=process.argv[1].split(".");process.stdin.on("data",c=>s+=c).on("end",()=>{try{let v=JSON.parse(s);for(const k of p)v=v?.[k];process.stdout.write(String(v??""))}catch{}})' "$1" 2>/dev/null && return 0
  fi
  printf '%s' "$payload" | sed -nE "s/.*\"${1##*.}\"[[:space:]]*:[[:space:]]*\"(([^\"\\]|\\.)*)\".*/\\1/p"
}
extract_cmd() {
  payload_field tool_input.command
}
# NOT called here on purpose. `payload_field` may spawn a process, and
# `routing-watch.sh` — which includes this partial and runs after EVERY tool call
# in every session — never reads `cmd`. Each consumer that wants it calls
# `extract_cmd` itself, at the point where it already knows it needs it.

navori_audit_name="subagent-no-background"
navori_audit_phase="PreToolUse"
# Fallback no-ops, overwritten by the real definitions the include brings in.
# FAIL-OPEN: an undefined function under `set -e` would be exit 127, and a
# recorder that can kill the thing it observes is the one bug this partial may
# never have.
navori_audit_begin() { :; }
navori_audit_log() { :; }
# Shared audit repository resolver (#764) — inlined into every audit hook at
# render time. A nested agent worktree lives below the repository's
# `.claude/worktrees/` directory, but its basename is an ephemeral agent id.
#
# navori_audit_repo_from_cwd <cwd> — prints the stable parent repo name.
# This only uses shell builtins before the existing `basename` call: audit hooks
# run often, so discovering the Git common directory would add an avoidable fork
# per invocation.
navori_audit_repo_from_cwd() {
  navori_audit_repo_cwd=$1
  case "$navori_audit_repo_cwd" in
    */.claude/worktrees | */.claude/worktrees/*)
      navori_audit_repo_cwd=${navori_audit_repo_cwd%%/.claude/worktrees*}
      ;;
  esac
  basename "$navori_audit_repo_cwd" 2>/dev/null
}
# Shared audit-mode event recorder — inlined into each managed hook at render
# time (see the include directive in the source scripts + lib/render/hook-includes.ts).
#
# WHY (spec 0013): a hook is only visible to the transcript when it BLOCKS or
# INJECTS context. Every hook that runs and lets the action through is invisible,
# so `navori audit` could never answer "did the gate run, and what did it cost?".
# The transcript cannot be fixed — it is the host's format — so the harness
# records its own execution instead, and the session log becomes the source of
# truth for what the harness did.
#
# Expects `$payload` (the raw hook payload on stdin) to be in scope, and reads
# `$navori_audit_t0` for the start instant. Both are set by `navori_audit_begin`.
#
# Every variable read here carries a `:-` default ON PURPOSE: most managed hooks
# run under `set -euo pipefail`, where an unset variable ABORTS the hook. A
# recorder that can abort the thing it observes is worse than no recorder, so the
# partial must be safe to inline into `set -u` and `set +e` alike.
#
# FAIL-OPEN ABSOLUTE, and this matters more here than anywhere else: this code is
# inlined into hooks whose own contract is to never break a session. Observation
# must never become the reason an action fails, so every path returns 0 and
# nothing is ever written to stdout — a stray byte there would be interpreted by
# the host as hook output (context injection, or a block reason).

# Start the clock — but only after establishing that anything will be recorded.
#
# THE COST OF BEING OFF is the number that matters here: this code is inlined
# into hooks that fire on EVERY Bash call, and audit-mode is off for virtually
# every session of every user. An earlier version ran `perl` plus two `jq`
# invocations before it ever checked whether a log existed — three processes per
# hook, four hooks per command, ~48 ms on every single shell call for a feature
# nobody had turned on.
#
# So the gate is a pure-builtin one first: the per-repo audit directory only
# exists once audit-mode has been activated in this repo at least once. No
# subprocess, no parsing. Everything expensive lives behind it.
navori_audit_begin() {
  navori_audit_on=0

  navori_audit_root=${NAVORI_AUDITS_ROOT:-}
  if [ -z "$navori_audit_root" ]; then
    [ -n "${HOME:-}" ] || return 0
    navori_audit_root=$HOME/.navori/audits
  fi

  # The gate tests the audit ROOT, not the per-repo directory.
  #
  # Deriving the repo cheaply would mean `${CLAUDE_PROJECT_DIR##*/}` — and that
  # is WRONG: the authoritative repo comes from the payload's `cwd`, and the two
  # differ whenever a hook fires inside an agent worktree, since the hook process
  # starts in the main repo (#454). A gate built on the wrong name would silently
  # record nothing exactly where the harness runs its parallel work.
  #
  # The root alone is enough for what this gate is for: a user who has never
  # activated audit-mode anywhere has no `~/.navori/audits`, so the common case
  # costs one stat and zero processes. Someone who does use audit-mode pays the
  # parsing — which is the cost of the feature they turned on.
  [ -d "$navori_audit_root" ] || return 0

  navori_audit_on=1
  navori_audit_t0=$(navori_audit_now)
}

# Milliseconds since epoch, spending a process only when it has to.
#
# `$EPOCHREALTIME` is a BUILTIN in bash 5 and in zsh (with zsh/datetime, which
# the harness's zsh path already has): no fork at all. Only a shell without it
# pays for `perl`, and only a machine without perl degrades to whole seconds —
# `date` has no portable millisecond format (GNU has %s%3N, BSD does not).
navori_audit_now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    # `1756... .123456` → milliseconds, with pure parameter expansion.
    navori_audit_epoch=${EPOCHREALTIME/,/.}
    printf '%s%s' "${navori_audit_epoch%%.*}" "$(printf '%.3s' "${navori_audit_epoch#*.}")"
    return 0
  fi
  perl -MTime::HiRes=time -e 'printf "%.0f", time*1000' 2>/dev/null \
    || printf '%s' $(( $(date +%s 2>/dev/null || echo 0) * 1000 ))
}

# navori_audit_log <verdict> [reason]
#
# `name`, `phase`, `tool` and `source` come from the caller's own variables,
# which the render sets per hook — the partial never guesses which hook it is
# inlined into.
navori_audit_log() {
  # The builtin-only gate from `navori_audit_begin`: when audit-mode was never
  # activated in this repo, nothing below runs and no process is spawned.
  [ "${navori_audit_on:-0}" = "1" ] || return 0
  # No payload, no jq, no clock → nothing to record. Each of these is a normal
  # state for a hook that bailed early, not an error worth surfacing.
  [ -n "${payload:-}" ] || return 0
  command -v jq >/dev/null 2>&1 || return 0

  # ONE jq for every field, not one per field: this runs on each hook of each
  # Bash call, and a fork is the most expensive thing in it. Newline-separated,
  # read back positionally.
  # The third field is the OWNER, and it is never empty: inside a subagent the
  # host sends a real `agent_id`; on the main thread it sends none and the
  # literal below names the orchestrator explicitly.
  #
  # It used to be `// ""`, and the empty case did not stay empty — it came out
  # as the `cwd`. Command substitution strips trailing newlines, so an empty
  # third field left `$navori_audit_fields` with only two lines; then
  # `${rest#*<NL>}` found no newline in `"cwd"` and POSIX says a `#` pattern
  # that does not match returns the string UNCHANGED. 41,581 of the park's
  # 52,460 recorded owners (79%) were a filesystem path for that reason.
  #
  # The consumer's behaviour does not change — `ownerOf` looks the value up
  # among the session's agents and sends anything that names nobody to the
  # orchestrator, which is where a path already went — but the record stops
  # claiming the repo directory is an agent. Old logs keep working through the
  # same "names nobody" branch.
  #
  # The trailing "." is a sentinel, not data: with it the third field is always
  # followed by a newline, so the `%%` below cannot fall into the same trap if
  # a future field is ever empty.
  #
  # The owner is picked with an explicit "first non-empty string", NOT with
  # `.agent_id // .subagent_id // "orchestrator"`. In jq only `null` and `false`
  # are falsy, so a host that sends the key with an EMPTY string satisfies `//`
  # and the chain yields `""` — the field then disappears from the record and
  # `ownerOf` falls back to the time window, which is the guess this field
  # exists to avoid. Caught by a test, not by review.
  navori_audit_fields=$(printf '%s' "${payload:-}" | jq -r '[.session_id // "", .cwd // "", ([.agent_id, .subagent_id] | map(select(type == "string" and . != "")) | first) // "orchestrator", .tool_use_id // "", "."] | .[]' 2>/dev/null) || return 0
  navori_audit_session=${navori_audit_fields%%
*}
  navori_audit_rest=${navori_audit_fields#*
}
  navori_audit_cwd=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_agent=${navori_audit_rest%%
*}
  navori_audit_rest=${navori_audit_rest#*
}
  navori_audit_tool_use_id=${navori_audit_rest%%
*}
  [ -n "$navori_audit_session" ] || return 0
  # Same character class the CLI enforces (#503): the id composes a path, so
  # anything path-shaped means the payload is not what we think it is.
  case "$navori_audit_session" in
    *[!A-Za-z0-9_-]*) return 0 ;;
  esac

  [ -n "$navori_audit_cwd" ] || navori_audit_cwd=$PWD
  navori_audit_repo=$(navori_audit_repo_from_cwd "$navori_audit_cwd") || return 0
  [ -n "$navori_audit_repo" ] || return 0

  navori_audit_file=$navori_audit_root/$navori_audit_repo/session-$navori_audit_session.log

  # The session may not be the marked one even in a repo that has been audited
  # before. Also the writability check — a log that cannot be appended to is not
  # an error, it is simply not recording.
  if [ ! -f "$navori_audit_file" ]; then
    # SPOOL for the phase that CANNOT have a log yet (#778).
    #
    # `navori audit --start` is what creates the session log, and it runs from
    # the UserPromptSubmit hook — i.e. after the first prompt. Every SessionStart
    # hook therefore fires BEFORE the file exists, and the check above threw its
    # record away every single time: measured, `session-start-context` recorded 1
    # of ~20 startups in this repo, and the only survivor was a resume onto an
    # already-open log. "Did the session load the harness?" had no witness at all,
    # which is exactly the question the recorder exists to answer.
    #
    # So those records go to a side file that `--start` absorbs. Two deliberate
    # limits keep this from becoming a leak:
    #
    #   1. SessionStart ONLY. Every other phase runs after a prompt, so a missing
    #      log there means the session is genuinely not marked — and spooling
    #      those would write four lines per Bash call, for every session of every
    #      repo, forever. That is thousands of writes to buy nothing.
    #   2. Only where the repo's audit directory ALREADY exists, which means the
    #      repo has been audited (or armed) at least once. `mkdir` is never run
    #      from here: a repo that has never used audit-mode must stay at zero
    #      files and zero forks, the same contract as the root gate above. The
    #      cost is that the FIRST audited session of a repo still loses its
    #      SessionStart records; every one after it has them.
    #
    # FAIL-OPEN, and here more than anywhere: this runs while a session is
    # opening. Every failure path below returns 0 and writes nothing to stdout —
    # a spool that could abort a hook would make observation the reason a session
    # does not start, which is the one bug this partial may never have.
    [ "${navori_audit_phase:-}" = "SessionStart" ] || return 0
    [ -d "$navori_audit_root/$navori_audit_repo" ] || return 0
    navori_audit_file=$navori_audit_root/$navori_audit_repo/pending-$navori_audit_session.jsonl
    if [ ! -e "$navori_audit_file" ]; then
      : >> "$navori_audit_file" 2>/dev/null || return 0
    fi
  fi
  [ -w "$navori_audit_file" ] || return 0

  # Volume valve, OFF by default.
  #
  # `PreToolUse(Bash)` chains four hooks, so every shell command leaves four
  # lines and most are `skip` — a long session runs to thousands. Set
  # NAVORI_AUDIT_SKIP_NOOPS=1 to drop the ones that did nothing.
  #
  # Default off on purpose: a `skip` is the ONLY evidence that a hook ran and
  # decided it had no business acting, which is exactly what distinguishes it
  # from a hook that never executed — the question that motivated recording
  # hooks at all. The valve trades that away knowingly; it must not be the
  # silent default.
  if [ "${NAVORI_AUDIT_SKIP_NOOPS:-0}" = "1" ]; then
    case "$1" in
      skip|noop) return 0 ;;
    esac
  fi

  navori_audit_end=$(navori_audit_now)
  navori_audit_ms=$(( navori_audit_end - ${navori_audit_t0:-$navori_audit_end} ))
  [ "$navori_audit_ms" -ge 0 ] 2>/dev/null || navori_audit_ms=0

  # `tsMs` is the instant at the resolution the log actually needs (#685): the
  # `ts` below truncates to the second, and 84% of a measured session's events
  # share their second with another one. This value is already computed — the
  # duration above is derived from it — so recording it costs nothing.
  #
  # Validated with the same `-ge 0` idiom as `ms`, and for the same reason: it
  # is passed as `--argjson`, so a non-numeric value would make the whole `jq`
  # fail and the event would vanish instead of merely losing a field.
  [ "$navori_audit_end" -ge 0 ] 2>/dev/null || navori_audit_end=0

  # `ts` is NOT stamped here, and that is the whole point of #696: it was a
  # `date` fork per event — 46,850 of them across this store — for a string
  # fully derivable from the `tsMs` above, which `$EPOCHREALTIME` already
  # produced without spawning anything. The file's own cost doctrine (see
  # `navori_audit_now`) says spend a process only when there is no other way;
  # keeping this one made the comment lie four lines under the value that
  # refutes it.
  #
  # Nothing downstream lost a field: `parse.ts` derives the ISO from `tsMs`
  # when the record carries none, and logs written before this still have
  # theirs. The lifecycle records — `start`, `stop`, `session-end` — keep a real
  # `ts`, so a human reading the raw `.log` still has dated anchors; those are
  # ~3 per session, not one per hook.
  # `navori_audit_agent` came out of the same single jq above. It is what lets
  # the report attribute a hook to a subagent WITHOUT guessing: with agents
  # running in parallel their time windows overlap, so attribution by timestamp
  # is the fallback, not the primary route.
  #
  # It is recorded, never trusted as an agent identity by itself (#560). What
  # `.agent_id` means depends on the PHASE: on the tool phases it is stable —
  # 485 events of one measured session carried 11 distinct ids, and the
  # subagents' resolved to real transcripts — but on `SubagentStop` the host
  # sends a fresh id per firing: 112 distinct ids for 117 firings, 102 of them
  # matching nothing under `~/.claude`. So a consumer that resolves this field
  # must treat "names nobody" as invalid data rather than as a different agent
  # (`ownerOf` in `lib/audit/parse.ts` is where that rule lives).

  printf '%s\n' "$(jq -cn \
    --arg name "${navori_audit_name:-unknown}" \
    --arg phase "${navori_audit_phase:-unknown}" \
    --arg verdict "${1:-unknown}" \
    --arg reason "${2:-}" \
    --arg tool "${navori_audit_tool:-}" \
    --arg src "${navori_audit_source:-core}" \
    --arg agent "${navori_audit_agent:-}" \
    --arg toolUseId "${navori_audit_tool_use_id:-}" \
    --argjson ms "$navori_audit_ms" \
    --argjson tsMs "$navori_audit_end" \
    '{tsMs:$tsMs,event:"hook",name:$name,phase:$phase,verdict:$verdict,ms:$ms,source:$src}
     + (if $tool   == "" then {} else {tool:$tool}       end)
     + (if $reason == "" then {} else {reason:$reason}   end)
     + (if $agent  == "" then {} else {agentId:$agent}   end)
     + (if $toolUseId == "" then {} else {toolUseId:$toolUseId} end)' 2>/dev/null)" \
    >> "$navori_audit_file" 2>/dev/null

  return 0
}
navori_audit_begin

navori_audit_verdict="allow"
navori_audit_reason=""
navori_audit_on_exit() {
  navori_audit_log "$navori_audit_verdict" "$navori_audit_reason" || true
  return 0
}
trap navori_audit_on_exit EXIT

# THE CHEAP GATE. This fires on EVERY Bash/Monitor call from EVERY agent (and
# the main thread); only a subagent is ever in scope. Fork-free PRESENCE test
# before anything that spawns a process — the main thread carries no
# `agent_id` key at all, so a plain substring test already proves absence
# without a fork.
case "$payload" in
  *'"agent_id"'*) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="sin agent_id (hilo principal)"
    exit 0
    ;;
esac

navori_tool=$(payload_field tool_name)

block() {
  echo "[navori] BLOCKED by subagent-no-background: $1" >&2
  echo "[navori] a subagent does not background its own work (verify-before-done: run chained steps one by one in the foreground, or report Status: BLOCKED)." >&2
  navori_audit_verdict="block"
  navori_audit_reason="$1"
  exit 2
}

case "$navori_tool" in
  Monitor)
    block "Monitor dentro de un subagente"
    ;;
  Bash) ;;
  *)
    navori_audit_verdict="skip"
    navori_audit_reason="tool_name no cubierto"
    exit 0
    ;;
esac

navori_bg=$(payload_field tool_input.run_in_background)
if [ "$navori_bg" = "true" ]; then
  block "Bash run_in_background dentro de un subagente"
fi

navori_audit_verdict="allow"
navori_audit_reason="no backgrounded"
exit 0
# navori:managed end id="subagent-no-background-base"
